In [2]:
import pandas as pd
import numpy as np

In [49]:
df=pd.read_csv("WebExtract.txt")
#df=df[np.isfinite(df['SCORE'])]

In [50]:
df['SD'] = df['SE'] = df.SCORE

In [51]:
df.INSPDATE=pd.to_datetime(df.INSPDATE)
df.GRADEDATE=pd.to_datetime(df.GRADEDATE)
df.RECORDDATE=pd.to_datetime(df.RECORDDATE)
c=df.groupby("CAMIS").apply(lambda x: x.sort_values(by='INSPDATE',ascending=False).head(1))
c

,,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,SD,SE
CAMIS,,,,,,,,,,,,,,,,,,
30075445,0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03,D,10F,2,A,2014-03-03,2014-09-04 06:01:28.403,2,2
30112340,1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,06A,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
30191841,2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10B,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
40356018,6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10,D,10F,5,A,2014-06-10,2014-09-04 06:01:28.403,5,5
40356068,56265,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2014-01-29,P,08A,12,NaN,NaT,2014-09-04 06:01:28.403,12,12
40356151,19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06D,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10
40356442,15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,10H,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
40356483,3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,08C,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
40356649,11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06A,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12
40356731,9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,10F,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12
40357217,13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10I,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
40357437,30,40357437,C & C CATERING SERVICE,3,7715,18 AVENUE,11214,7182322800,3,2014-04-16,D,06D,5,A,2014-04-16,2014-09-04 06:01:28.403,5,5
40358429,56373,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2014-08-08,F,08A,50,NaN,NaT,2014-09-04 06:01:28.403,50,50
40359480,21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07,D,10B,3,A,2014-05-07,2014-09-04 06:01:28.403,3,3
40359705,48983,40359705,NATHAN'S FAMOUS,3,1310,SURF AVENUE,11224,7183332202,41,2013-12-03,D,10F,5,A,2013-12-03,2014-09-04 06:01:28.403,5,5
40360045,23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10,D,04L,13,A,2013-10-10,2014-09-04 06:01:28.403,13,13
40360076,43,40360076,CARVEL ICE CREAM,3,203,CHURCH AVENUE ...,11218,7184389501,43,2014-02-10,D,10F,2,A,2014-02-10,2014-09-04 06:01:28.403,2,2
40361322,33,40361322,CARVEL ICE CREAM,4,265-15,HILLSIDE AVENUE ...,11004,7183430392,43,2013-09-18,D,08A,10,A,2013-09-18,2014-09-04 06:01:28.403,10,10
40361390,36,40361390,NORDIC DELICACIES,3,6909,3 AVENUE,11209,7187481874,27,2014-08-21,D,10B,4,A,2014-08-21,2014-09-04 06:01:28.403,4,4
40361521,17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02,U,04C,19,Z,2014-09-02,2014-09-04 06:01:28.403,19,19
40361606,41,40361606,THE MOVABLE FEAST,3,284,PROSPECT PARK WEST,11215,7189652900,3,2013-11-14,D,10F,2,A,2013-11-14,2014-09-04 06:01:28.403,2,2
40361618,34,40361618,SAL'S DELI,4,129-08,20 AVENUE,11356,7186619498,27,2014-08-16,D,06C,12,A,2014-08-16,2014-09-04 06:01:28.403,12,12
40361708,38,40361708,BULLY'S DELI,1,759,BROADWAY ...,10003,2122549755,27,2014-01-21,D,06D,12,A,2014-01-21,2014-09-04 06:01:28.403,12,12
40361998,48985,40361998,STEVE CHU'S DELI & GROCERY,4,3406,10 STREET ...,11106,7187268888,27,2014-03-19,D,10F,3,A,2014-03-19,2014-09-04 06:01:28.403,3,3
40362098,47,40362098,HARRIET'S KITCHEN,1,502,AMSTERDAM AVENUE ...,10024,2127210045,18,2014-03-04,U,04N,13,A,2014-03-04,2014-09-04 06:01:28.403,13,13
40362264,56701,40362264,P & S DELI GROCERY,1,730,COLUMBUS AVENUE,10025,2129323030,3,2014-08-18,P,04L,24,NaN,NaT,2014-09-04 06:01:28.403,24,24
40362274,68,40362274,ANGELIKA FILM CENTER,1,18,WEST HOUSTON STREET,10012,2129952570,3,2014-04-03,D,06D,9,A,2014-04-03,2014-09-04 06:01:28.403,9,9
40362344,50,40362344,WHITE CASTLE,3,531,MYRTLE AVENUE,11205,7188578132,39,2014-03-18,D,06D,8,A,2014-03-18,2014-09-04 06:01:28.403,8,8
40362432,63,40362432,HO MEI RESTAURANT,4,103-05,37 AVENUE,11368,7187796903,20,2014-04-21,D,06C,10,A,2014-04-21,2014-09-04 06:01:28.403,10,10
40362715,52,40362715,THE COUNTRY CAFE,1,60,WALL STREET,10005,3474279132,83,2013-09-18,D,06B,13,A,2013-09-18,2014-09-04 06:01:28.403,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50014014,468718,50014014,XIUN WEI CHINESE RESTAURANT,2,122,WESTCHESTER SQUARE,10461,7188636888,20,2014-08-27,B,NaN,0,N,NaT,2014-09-04 06:01:28.403,0,0
50014020,468493,50014020,DHRUV'S KATI SHACK FACTORY,4,180-10,UNION TURNPIKE ...,11366,7183431680,44,2014-08-25,D,10F,3,N,NaT,2014-09-04 06:01:28.403,3,3
50014021,435865,50014021,TASTY LIGHT CUSINE,2,737,LYDIG AVENUE,10462,3478101234,77,2014-08-22,D,10F,3,N,NaT,2014-09-04 06:01:28.403,3,3
50014038,40266,50014038,Mi Mexico Lindo,2,587,SOUTHERN BOULEVARD,10455,3472717830,55,2014-09-02,D,02G,12,A,2014-09-02,2014-09-04 06:01:28.403,12,12
50014083,426950,50014083,"MICHAEL & SOPHIA'S PIZZERIA, INC.",3,2224,AVENUE U,11229,7187692200,63,2014-08-21,D,10F,11,N,NaT,2014-09-04 06:01:28.403,11,11
50014086,468304,50014086,SUSHI PARA MANHATTAN,1,1461,3 AVENUE,10028,2125850300,49,2014-08-26,D,10F,2,N,NaT,2014-09-04 06:01:28.403,2,2
50014089,468305,50014089,HANG OUT 58,3,5816,FORT HAMILTON PARKWAY ...,11219,7188511268,52,2014-08-20,D,10F,2,N,NaT,2014-09-04 06:01:28.403,2,2
50014098,434866,50014098,DUNKIN DONUTS,3,272,BROADWAY ...,11211,7183880847,29,2014-09-02,P,06C,16,N,NaT,2014-09-04 06:01:28.403,16,16
50014104,468625,50014104,DELI AND PIZZA,3,603,AVENUE Z,11223,7186487775,3,2014-09-02,F,04N,30,N,NaT,2014-09-04 06:01:28.403,30,30
50014153,468306,50014153,VAN09 INC,1,181,ESSEX STREET ...,10002,2124771455,53,2014-08-21,D,08A,13,N,NaT,2014-09-04 06:01:28.403,13,13
50014187,468627,50014187,MATISA,3,3917,4 AVENUE ...,11232,9177536981,3,2014-08-21,E,04L,41,N,NaT,2014-09-04 06:01:28.403,41,41
50014212,435866,50014212,CHICKEN SHACK,4,36-19,BROADWAY,11106,7187213035,18,2014-09-02,P,06C,27,N,NaT,2014-09-04 06:01:28.403,27,27
50014220,434867,50014220,HIBACHI EXPRESS DUMPLING,1,229,1 AVENUE ...,10003,9175775907,22,2014-09-02,G,05E,53,N,NaT,2014-09-04 06:01:28.403,53,53
50014226,468308,50014226,EL GRAN VALLE IV RESTAURANT,1,1944,AMSTERDAM AVENUE,10032,2123687100,77,2014-08-19,D,10F,19,N,NaT,2014-09-04 06:01:28.403,19,19
50014233,434868,50014233,Q'KACHAPA,1,1552,SAINT NICHOLAS AVENUE ...,10040,3474320002,99,2014-08-21,D,10H,6,N,NaT,2014-09-04 06:01:28.403,6,6
50014251,426951,50014251,MR.ROTI LLC,1,1196,AVENUE OF THE AMERICAS,10036,2122211400,99,2014-08-25,E,10A,32,N,NaT,2014-09-04 06:01:28.403,32,32
50014266,426952,50014266,NYU - TORCH CLUB,1,18,WAVERLY PLACE,10003,2129929163,3,2014-09-02,F,02B,45,N,NaT,2014-09-04 06:01:28.403,45,45
50014289,426956,50014289,BETTY BROOKLYN CATERING CO.,3,455,UTICA AVENUE ...,11203,7188323889,3,2014-08-25,D,06C,9,N,NaT,2014-09-04 06:01:28.403,9,9
50014316,468809,50014316,RALPH LAUREN,1,711,5 AVENUE,10022,2123551829,99,2014-08-22,D,10J,2,N,NaT,2014-09-04 06:01:28.403,2,2
50014318,468636,50014318,VOGA LOUNGE & GRILL,1,300,AUDUBON AVENUE,10033,2123908490,77,2014-08-29,D,10A,5,N,NaT,2014-09-04 06:01:28.403,5,5
50014331,426958,50014331,LUEN HOP CHINESE KITCHEN,4,118-33,GUY R BREWER BOULEVARD,11434,7185255366,20,2014-08-28,P,04L,20,N,NaT,2014-09-04 06:01:28.403,20,20
50014333,468497,50014333,FOODBELLA LLC,1,3,EAST 53 STREET,10022,516_582_55,99,2014-08-29,E,05E,28,N,NaT,2014-09-04 06:01:28.403,28,28
50014385,426959,50014385,PAPRIKA,1,110,SAINT MARKS PLACE,10009,2126776563,48,2014-08-27,F,02G,33,N,NaT,2014-09-04 06:01:28.403,33,33
50014414,426962,50014414,BURGER HEAVEN,1,20,EAST 49 STREET,10017,2127552166,3,2014-08-29,P,02H,20,N,NaT,2014-09-04 06:01:28.403,20,20
50014461,426963,50014461,YUMMY CHINESE RESTAURANT,3,1195,FLATBUSH AVENUE,11226,7184348652,20,2014-09-02,F,02G,35,N,NaT,2014-09-04 06:01:28.403,35,35
50014465,434871,50014465,MIYABI SUSHI & ASIAN CUISINE,1,118,WEST 3 STREET ...,10012,2122281688,99,2014-08-29,D,10A,3,N,NaT,2014-09-04 06:01:28.403,3,3
50014483,468641,50014483,MARTINIELLO'S PIZZARIA,4,675,ONDERDONK AVENUE,11385,3479161959,62,2014-08-27,D,10A,2,N,NaT,2014-09-04 06:01:28.403,2,2
50014494,468643,50014494,BLUE PARROT BAR,3,3219,FULTON STREET,11208,3473934602,99,2014-08-28,D,10H,9,N,NaT,2014-09-04 06:01:28.403,9,9
50014708,426965,50014708,PALM GROVE TAKE OUT RESTAURANT,3,4122,AVENUE D,11203,7184218898,44,2014-08-28,D,05D,24,N,NaT,2014-09-04 06:01:28.403,24,24
50014831,48996,50014831,"OAXACA GREENWICH,LLC",1,48,GREENWICH AVENUE,10011,2123664488,55,2014-09-02,D,02G,10,A,2014-09-02,2014-09-04 06:01:28.403,10,10

In [52]:
#Dataframe sorted by 
def SE(x):
    n=np.sqrt(x.count())
    if n==0:
        return None
    ans=np.std(x)
    return(ans)
a=c.groupby('ZIPCODE').agg({"CAMIS":lambda x: x.nunique(),"SCORE":pd.Series.mean,"SD":pd.Series.std,"SE":pd.Series.sem})

a
#b=a.CAMIS.nunique().sort_values(ascending=False).head(100)

             SCORE  CAMIS        SE         SD
ZIPCODE
7005     11.000000      1       NaN        NaN
10000    13.000000      1       NaN        NaN
10001     9.149495    495  0.303667   6.756154
10002    12.006608    454  0.399362   8.509309
10003    11.951368    658  0.326563   8.376822
10004    11.070866    127  0.644473   7.262844
10005     9.455882     68  0.901524   7.434156
10006    12.608696     46  1.219994   8.274400
10007    11.114504    131  0.527643   6.039156
10009    11.858086    303  0.412878   7.186931
10010    11.543933    239  0.519905   8.037540
10011    11.757370    441  0.378271   7.943699
10012    11.774684    395  0.364305   7.240423
10013    12.252155    464  0.362880   7.816676
10014    11.766917    399  0.399393   7.977878
10016    11.985075    402  0.429073   8.602892
10017    11.409341    364  0.415452   7.926315
10018    11.836923    325  0.433918   7.822561
10019    10.760802    648  0.280962   7.152125
10020     8.382979     47  0.789356   5.411554
10021    12.590604    149  0.621214   7.582887
10022    10.974630    473  0.336193   7.311718
10023    11.020833    192  0.554115   7.678049
10024    11.682051    195  0.517581   7.227627
10025    12.004367    229  0.570593   8.634639
10026    13.638889     72  1.075278   9.124037
10027    11.348101    158  0.579274   7.281358
10028    11.611374    211  0.533553   7.750310
10029    12.115183    191  0.695168   9.607417
10030     9.216216     37  1.163209   7.075526
...            ...    ...       ...        ...
11411    12.200000     20  1.236719   5.530775
11412     9.023256     43  1.194992   7.836084
11413    12.256410     39  1.795074  11.210235
11414    13.595745     47  1.237578   8.484409
11415    15.583333     36  2.450583  14.703498
11416    13.000000     43  1.261931   8.275034
11417    11.666667     66  0.939507   7.632589
11418    11.904762     84  0.986806   9.044227
11419    13.137931     87  0.890739   8.308265
11420    11.083333     84  0.811069   7.433575
11421    11.171429     70  0.910480   7.617622
11422    11.820513     39  1.561977   9.754545
11423    11.914286     35  1.052705   6.227885
11426    10.178571     28  0.930173   4.922011
11427    10.333333     18  0.740959   3.143621
11428    13.945946     37  1.360614   8.276291
11429    13.833333     24  1.806456   8.849793
11430     9.689655    145  0.730593   8.797504
11432    11.540541    185  0.607386   8.261338
11433    11.793103     29  1.171689   6.309739
11434    12.372093     86  1.112674  10.318512
11435    10.922330    103  0.661798   6.716514
11436    10.304348     23  0.883388   4.236581
11451     5.000000      1       NaN        NaN
11691    13.000000     44  1.637948  10.864921
11692    10.000000      9  1.589899   4.769696
11693    12.666667     27  1.558910   8.100332
11694    14.333333     36  1.756168  10.537010
11697    15.500000      2  5.500000   7.778175
11753    11.000000      1       NaN        NaN

[207 rows x 4 columns]

In [53]:
topzipcodes=a[a.CAMIS>100].sort_values('SCORE',ascending=False)
topzipcodes["ZIPCODE"]=topzipcodes.index
topzipcodes.shape
topzipcodes.head(5)
#topzipcodes[1]

#a=pd.DataFrame({a:topzipcodes.ZIPCODE,b:topzipcodes.SD})
topzipcodes= topzipcodes[['ZIPCODE', 'SCORE', 'SE', 'CAMIS']]
topzipcodes.ZIPCODE=topzipcodes.ZIPCODE.apply(int)
#topzipcodes.CAMIS.apply(int)
topzipcodes.CAMIS=topzipcodes.CAMIS.apply(int)
topzipcodes.shape
topzipcodes

         ZIPCODE      SCORE        SE  CAMIS
ZIPCODE
11355      11355  14.021390  0.689713    187
11104      11104  13.372727  0.877849    110
11220      11220  13.334426  0.539648    305
11235      11235  13.290698  0.912488    172
10033      10033  13.132743  0.720775    113
11377      11377  13.111650  0.680649    206
11354      11354  13.110465  0.562352    344
10032      10032  12.913043  1.002557    115
11372      11372  12.857605  0.508757    309
11249      11249  12.836735  0.810715    147
11229      11229  12.688406  0.843629    138
10021      10021  12.590604  0.621214    149
10128      10128  12.573248  0.905064    157
11211      11211  12.402299  0.481563    348
11214      11214  12.371429  0.638935    175
11216      11216  12.320755  0.749350    159
11203      11203  12.281481  0.683991    135
11223      11223  12.275281  0.690862    178
10013      10013  12.252155  0.362880    464
11205      11205  12.187500  0.647448    144
10314      10314  12.115385  0.524449    182
10029      10029  12.115183  0.695168    191
10002      10002  12.006608  0.399362    454
10025      10025  12.004367  0.570593    229
11208      11208  11.991150  0.786812    113
10016      10016  11.985075  0.429073    402
11219      11219  11.980198  0.938187    101
11358      11358  11.963504  0.673791    137
10003      10003  11.951368  0.326563    658
11206      11206  11.865248  0.755810    141
...          ...        ...       ...    ...
11222      11222  11.145946  0.523453    185
11232      11232  11.141509  0.829319    106
10036      10036  11.137694  0.326991    581
10007      10007  11.114504  0.527643    131
11207      11207  11.101562  0.613159    128
10004      10004  11.070866  0.644473    127
10468      10468  11.049020  0.749345    102
10023      10023  11.020833  0.554115    192
10458      10458  11.000000  0.543845    188
10022      10022  10.974630  0.336193    473
10463      10463  10.968254  0.679022    126
11435      11435  10.922330  0.661798    103
10065      10065  10.904192  0.424456    167
11105      11105  10.773109  0.672621    119
11201      11201  10.768769  0.409478    333
10019      10019  10.760802  0.280962    648
11209      11209  10.691700  0.522052    253
10461      10461  10.677852  0.590009    149
11237      11237  10.600000  0.529398    175
11231      11231  10.565789  0.511856    152
10462      10462  10.537931  0.499331    145
11368      11368  10.535714  0.452925    280
10306      10306  10.533333  0.476954    105
11217      11217  10.345528  0.426819    246
11234      11234  10.186207  0.506565    145
10472      10472  10.130841  0.630177    107
11236      11236   9.830189  0.727520    106
11430      11430   9.689655  0.730593    145
10001      10001   9.149495  0.303667    495
10451      10451   9.142857  0.538984    154

[87 rows x 4 columns]

In [54]:

a=[(str(int(row[1].ZIPCODE)),row[1].SCORE,row[1].SE,int(row[1].CAMIS)) for row in topzipcodes.iterrows()]
    #print (row[1].ZIPCODE,row[1].SCORE,row[1].SE,row[1].CAMIS)
a

[('11355', 14.021390374331551, 0.6897125233862571, 187),
 ('11104', 13.372727272727273, 0.87784890351321165, 110),
 ('11220', 13.334426229508196, 0.53964773490577722, 305),
 ('11235', 13.290697674418604, 0.91248843985678241, 172),
 ('10033', 13.132743362831858, 0.72077537009157799, 113),
 ('11377', 13.111650485436893, 0.68064879759666308, 206),
 ('11354', 13.11046511627907, 0.56235229508125062, 344),
 ('10032', 12.913043478260869, 1.0025570067842628, 115),
 ('11372', 12.857605177993527, 0.50875715649036657, 309),
 ('11249', 12.836734693877551, 0.81071479959675385, 147),
 ('11229', 12.688405797101449, 0.84362944752452096, 138),
 ('10021', 12.590604026845638, 0.62121434114745744, 149),
 ('10128', 12.573248407643312, 0.90506422758582861, 157),
 ('11211', 12.402298850574713, 0.48156307562019779, 348),
 ('11214', 12.371428571428572, 0.63893530956950906, 175),
 ('11216', 12.320754716981131, 0.74934999589350249, 159),
 ('11203', 12.281481481481482, 0.68399146011270728, 135),
 ('11223', 12.275280898876405, 0.6908620677251277, 178),
 ('10013', 12.252155172413794, 0.36288008406478817, 464),
 ('11205', 12.1875, 0.64744797785817043, 144),
 ('10314', 12.115384615384615, 0.52444861699043643, 182),
 ('10029', 12.115183246073299, 0.69516826267877996, 191),
 ('10002', 12.006607929515418, 0.39936167338274653, 454),
 ('10025', 12.004366812227074, 0.57059303552403706, 229),
 ('11208', 11.991150442477876, 0.78681208542975745, 113),
 ('10016', 11.985074626865671, 0.42907325720660194, 402),
 ('11219', 11.98019801980198, 0.93818660117152741, 101),
 ('11358', 11.963503649635037, 0.6737908208950798, 137),
 ('10003', 11.951367781155016, 0.32656252232399402, 658),
 ('11206', 11.865248226950355, 0.75580964043807464, 141),
 ('10009', 11.858085808580858, 0.41287840571400058, 303),
 ('10018', 11.836923076923076, 0.43391760876612417, 325),
 ('11375', 11.800000000000001, 0.48927227315891708, 190),
 ('10012', 11.774683544303798, 0.3643052098245475, 395),
 ('10014', 11.766917293233083, 0.39939346550689864, 399),
 ('10011', 11.757369614512472, 0.37827140054105302, 441),
 ('11221', 11.735849056603774, 0.90255720232390146, 106),
 ('11230', 11.712871287128714, 0.67153387795424779, 101),
 ('10024', 11.682051282051281, 0.51758112808250978, 195),
 ('11373', 11.639269406392694, 0.48483565106533255, 219),
 ('11226', 11.626262626262626, 0.66270054346960616, 198),
 ('10038', 11.617283950617283, 0.72703106807688567, 162),
 ('10028', 11.611374407582938, 0.53355331521886196, 211),
 ('10010', 11.543933054393305, 0.51990525920675157, 239),
 ('11432', 11.54054054054054, 0.60738565258160626, 185),
 ('11218', 11.450704225352112, 0.73888916189503751, 142),
 ('10017', 11.409340659340659, 0.41545178964684853, 364),
 ('11101', 11.404347826086957, 0.43493266823773663, 230),
 ('10467', 11.397515527950311, 0.58912765169585291, 161),
 ('10027', 11.348101265822784, 0.57927377649459688, 158),
 ('11103', 11.338308457711443, 0.48589546571651743, 201),
 ('11106', 11.318181818181818, 0.63381661331735539, 154),
 ('11385', 11.304526748971194, 0.42651039244316569, 243),
 ('11215', 11.302777777777777, 0.36885895247376321, 360),
 ('11204', 11.258333333333333, 0.6290689213033549, 120),
 ('11238', 11.253275109170305, 0.59433905427089972, 229),
 ('11361', 11.160714285714286, 0.68097817111478753, 112),
 ('11222', 11.145945945945947, 0.52345288406957879, 185),
 ('11232', 11.141509433962264, 0.82931884922681631, 106),
 ('10036', 11.137693631669535, 0.32699115213094465, 581),
 ('10007', 11.114503816793894, 0.52764349667736121, 131),
 ('11207', 11.1015625, 0.61315947983005414, 128),
 ('10004', 11.070866141732283, 0.64447321090975374, 127),
 ('10468', 11.049019607843137, 0.7493448184621061, 102),
 ('10023', 11.020833333333334, 0.55411548924547938, 192),
 ('10458', 11.0, 0.5438450483073628, 188),
 ('10022', 10.97463002114165, 0.33619314960615754, 473),
 ('10463', 10.968253968253968, 0.679022313768194, 126),
 ('11435', 10.922330097087379, 0.66179775238766303, 103),
 ('10065', 10.904191616766466, 0.42445562881598253, 167),
 ('11105', 10.77310924369748, 0.67262132907549987, 119),
 ('11201', 10.768768768768769, 0.40947826353605871, 333),
 ('10019', 10.760802469135802, 0.28096201864444975, 648),
 ('11209', 10.691699604743082, 0.52205201963477599, 253),
 ('10461', 10.677852348993289, 0.59000905836367623, 149),
 ('11237', 10.6, 0.52939845653341966, 175),
 ('11231', 10.565789473684211, 0.51185587025336043, 152),
 ('10462', 10.537931034482758, 0.49933103617084085, 145),
 ('11368', 10.535714285714286, 0.45292533338102903, 280),
 ('10306', 10.533333333333333, 0.47695360097680106, 105),
 ('11217', 10.345528455284553, 0.42681852286046729, 246),
 ('11234', 10.186206896551724, 0.50656477791473797, 145),
 ('10472', 10.130841121495328, 0.63017690039307217, 107),
 ('11236', 9.8301886792452837, 0.72751984230999112, 106),
 ('11430', 9.6896551724137936, 0.73059292310369783, 145),
 ('10001', 9.1494949494949491, 0.30366655760914535, 495),
 ('10451', 9.1428571428571423, 0.53898430442828926, 154)]

In [401]:
#topzipcodes.to_csv('a.csv',index=False)

In [458]:
#BY borough
b=c.groupby('BORO').agg({"CAMIS":lambda x: x.nunique(),"SCORE":pd.Series.mean,"SE":pd.Series.sem})

In [459]:
b=b.reset_index()

In [460]:

btuple=[(row[1].BORO,row[1].SCORE,row[1].SE,int(row[1].CAMIS)) for row in b.iterrows()]
btuple

[(0.0, 10.545454545454545, 1.6424130604561769, 12),
 (1.0, 11.358427436219156, 0.079815274485948259, 10201),
 (2.0, 10.72821670428894, 0.15200948403159781, 2365),
 (3.0, 11.472944108223567, 0.11071459149883139, 6072),
 (4.0, 11.755732423725602, 0.11121071258632133, 5625),
 (5.0, 11.712643678160919, 0.24903066158997716, 957)]

In [461]:
b

   BORO      SCORE  CAMIS        SE
0     0  10.545455     12  1.642413
1     1  11.358427  10201  0.079815
2     2  10.728217   2365  0.152009
3     3  11.472944   6072  0.110715
4     4  11.755732   5625  0.111211
5     5  11.712644    957  0.249031

In [464]:
#BY borough
b2=c.groupby('BORO').apply(lambda x: x.sort_values(by='CURRENTGRADE'))
b2

                         CAMIS                                       DBA  \
BORO
0    40959339 8214    40959339                   FRATELLI'S MARKET PLACE
     41289266 17965   41289266                                    SUBWAY
     41669940 30637   41669940                          STARBUCKS COFFEE
     41722563 33950   41722563                    PLACE TO BEACH CANTINA
     50003253 46262   50003253                            PARIS BAGUETTE
     50003719 38434   50003719                          NEW WIN HING INC
     50009623 40128   50009623          EL BOMBON POBLANO RESTAURANT INC
     50009993 48116   50009993  Little Neck Shanghai & Taiwanese Cuisine
     50011108 38013   50011108                                    SUBWAY
     50010945 433431  50010945                                    REVIVE
     50003629 36150   50003629                     ROSEDALE DELICATESSEN
     50013521 531641  50013521                           E E BAKERY INC.
1    30191841 2       30191841            DJ REYNOLDS PUB AND RESTAURANT
     41593113 27279   41593113                           TISANE PHARMACY
     41592830 27189   41592830                                    SUBWAY
     41592502 32639   41592502                                MOMO CAFFE
     41592474 27188   41592474                        HALE & HEARTY SOUP
     41592433 32638   41592433             INTERNATIONAL GOURMET KITCHEN
     41591881 27155   41591881                          WILLIAM BARNACLE
     41591834 27154   41591834                                      Ngam
     41591831 33005   41591831                   LA OAXAQUENA RESTAURANT
     41591687 27224   41591687                                  PIZZARTE
     41591587 27149   41591587                              BEST WINGERS
     41591488 27138   41591488                          ACQUA RESTAURANT
     41591211 32558   41591211                            MON PETIT CAFE
     41591002 27104   41591002                              UPSTAIRS BAR
     41593270 26316   41593270             MACMENAMINS NYC HELLS KITCHEN
     41590670 27099   41590670                              GOLDEN KRUST
     41590509 32333   41590509                 SHIH LEE CHINESE GOODEATS
     41590276 26232   41590276                    NUM PANG SANDWICH SHOP
...                        ...                                       ...
5    50013599 531589  50013599                      Fire Grilled Burgers
     50013641 531734  50013641                   ALFONSO'S PASTRY SHOPPE
     50013726 531492  50013726                             BROTHER PIZZA
     50013753 531736  50013753                             UNCLE LOUIE G
     50013966 435864  50013966                                    SUBWAY
     50014024 531439  50014024                                     ARENA
     50014170 531500  50014170                    SABOR Y TRADICION CORP
     50014387 531841  50014387                          TANGO MANGO, INC
     50014405 531757  50014405                PIQUETEADERO LA BELLA CORP
     50014447 531611  50014447                      NEW ISLAND TASTE INC
     50014492 531508  50014492                              CEYLON CURRY
     50014518 531903  50014518                               HARBOR EATS
     50014530 531904  50014530                    LEEYA PANDA GARDEN INC
     50014537 531905  50014537               1734 VICTORY BOULEVARD,INC.
     50014588 531851  50014588                           MD CREATORS LLC
     50014605 531764  50014605                 MORELOS DELI & FRUIT CORP
     50014650 531457  50014650                   GOOD WOK RESTAURANT INC
     50014668 531783  50014668                      W.H PANDA GARDEN INC
     50014670 531460  50014670                            CHINA BELL INC
     50014732 531915  50014732                       POPULAR CHICKEN INC
     50014761 531664  50014761                                    SUBWAY
     50014828 531465  50014828                          SURI KITCHEN INC
     50014874 531792  50014874                         IL POMODORO PIZZA
     50014885 531768  50014885                       CAMPANIA OF SI, INC
     50014920 531927  50014920                  FUSHIMI JAPANESE CUISINE
     50014935 531835  50014935                TWIN DRAGONS ASIAN CUISINE
     50014978 531521  50014978                         CARAVAN BAZAR INC
     50015012 531810  50015012                           NY FAMILY PIZZA
     50015034 531674  50015034                   EGGERS ICE CREAM PARLOR
     50015047 531524  50015047                       Parkside Pizza Corp

                      BORO    BUILDING  \
BORO
0    40959339 8214       0  0
     41289266 17965      0  32
     41669940 30637      0  9420
     41722563 33950      0  49
     50003253 46262      0  591
     50003719 38434      0  1180
     50009623 40128      0  7513
     50009993 48116      0  25220
     50011108 38013      0  1050
     50010945 433431     0  1240
     50003629 36150      0  24304
     50013521 531641     0         NaN
1    30191841 2          1         351
     41593113 27279      1         340
     41592830 27189      1  555
     41592502 32639      1  150-152
     41592474 27188      1  2284
     41592433 32638      1         505
     41591881 27155      1  80
     41591834 27154      1          99
     41591831 33005      1        1969
     41591687 27224      1          69
     41591587 27149      1         711
     41591488 27138      1  2123
     41591211 32558      1  801
     41591002 27104      1  59
     41593270 26316      1         500
     41590670 27099      1  12
     41590509 32333      1  311
     41590276 26232      1  140
...                    ...         ...
5    50013599 531589     5        3295
     50013641 531734     5  35
     50013726 531492     5  750
     50013753 531736     5  1210
     50013966 435864     5  2381
     50014024 531439     5  4916
     50014170 531500     5        2220
     50014387 531841     5         574
     50014405 531757     5           3
     50014447 531611     5  27
     50014492 531508     5  324
     50014518 531903     5        1000
     50014530 531904     5         128
     50014537 531905     5        1734
     50014588 531851     5       1281
     50014605 531764     5  6
     50014650 531457     5        375
     50014668 531783     5        1419
     50014670 531460     5  1068
     50014732 531915     5         229
     50014761 531664     5          86
     50014828 531465     5  12812
     50014874 531792     5  1778
     50014885 531768     5        3900
     50014920 531927     5        2110
     50014935 531835     5          54
     50014978 531521     5  1101
     50015012 531810     5        1880
     50015034 531674     5        6319
     50015047 531524     5  1547

                                                                 STREET  \
BORO
0    40959339 8214    WARDS ISLAND/2FL                              ...
     41289266 17965   Burke Avenue                                  ...
     41669940 30637   GUY R BREWER BOULEVARD                        ...
     41722563 33950   FANNY RD                                      ...
     50003253 46262   LEXINGTON AVE                                 ...
     50003719 38434   BAY ST                                        ...
     50009623 40128   ROOSEVELT AVE                                 ...
     50009993 48116   NORTHERN BLVD                                 ...
     50011108 38013   JACKSON AVE                                   ...
     50010945 433431  CLINTONVILLE ST                               ...
     50003629 36150   MERRICK BLVD                                  ...
     50013521 531641                                                NaN
1    30191841 2                                          WEST 57 STREET
     41593113 27279                                      EAST 86 STREET
     41592830 27189                    WEST   42 STREET
     41592502 32639   WEST   10 STREET                              ...
     41592474 27188   BROADWAY                                      ...
     41592433 32638                                            8 AVENUE
     41591881 27155   ST MARKS PLACE                                ...
     41591834 27154                                            3 AVENUE
     41591831 33005                                    AMSTERDAM AVENUE
     41591687 27224                                      WEST 55 STREET
     41591587 27149                                            2 AVENUE
     41591488 27138   PECK SLIP                                     ...
     41591211 32558   LEXINGTON AVENUE                              ...
     41591002 27104   WEST   46 STREET                              ...
     41593270 26316                                    WEST   43 STREET
     41590670 27099   GRAND CENTRAL STATION                         ...
     41590509 32333                    EAST   45 STREET
     41590276 26232   EAST   41 STREET                              ...
...                                                                 ...
5    50013599 531589                                         AMBOY ROAD
     50013641 531734  PAGE AVE                                      ...
     50013726 531492  PORT RICHMOND AVENUE                          ...
     50013753 531736  FOREST AVE                                    ...
     50013966 435864  HYLAN BOULEVARD                               ...
     50014024 531439  ARTHUR KILL ROAD                              ...
     50014170 531500                                      FOREST AVENUE
     50014387 531841                                         BAY STREET
     50014405 531757                                      CORSON AVENUE
     50014447 531611                   SEGUINE AVENUE
     50014492 531508  VICTORY BOULEVARD                             ...
     50014518 531903                                   RICHMOND TERRACE
     50014530 531904                                     LINCOLN AVENUE
     50014537 531905                                  VICTORY BOULEVARD
     50014588 531851                                   ARTHUR KILL ROAD
     50014605 531764  CEBRA AVENUE                                  ...
     50014650 531457                                    TOMPKINS AVENUE
     50014668 531783                                      FOREST AVENUE
     50014670 531460  CASTLETON AVENUE                              ...
     50014732 531915                                       BROAD STREET
     50014761 531664                                       GUYON AVENUE
     50014828 531465  LIBERTY AVE                                   ...
     50014874 531792  HYLAN BOULEVARD                               ...
     50014885 531768                                    RICHMOND AVENUE
     50014920 531927                                      RICHMOND ROAD
     50014935 531835                                   RICHMOND TERRACE
     50014978 531521  HYLAN BOULEVARD                               ...
     50015012 531810                                    HYLAN BOULEVARD
     50015034 531674                                         AMBOY ROAD
     50015047 531524  ARTHUR KILL ROAD                              ...

                      ZIPCODE       PHONE  CUISINECODE   INSPDATE ACTION  \
BORO
0    40959339 8214      10057  6466726722            3 2013-09-10      D
     41289266 17965     11753  2122480809           70 2014-02-20      D
     41669940 30637     11451  3042426200           14 2014-08-21      D
     41722563 33950      7005  7183735862           55 2014-04-18      D
     50003253 46262     10022  2128380404            8 2014-02-21      D
     50003719 38434     10305  7189815335           20 2014-08-11      D
     50009623 40128     11372  7186726500           77 2014-06-23      U
     50009993 48116     11362  7182251178            5 2014-05-20      D
     50011108 38013     11101  3477245334           69 2014-07-28      D
     50010945 433431    11357  7187477873           68 2014-08-20      P
     50003629 36150     11422  7185285528           27 2014-03-25      U
     50013521 531641      NaN  3475474481           99 1900-01-01    NaN
1    30191841 2         10019  2122452912            3 2013-07-22      D
     41593113 27279     10028  2125170037            3 2014-02-11      D
     41592830 27189     10036  2125945900           69 2014-08-08      D
     41592502 32639     10014  2124889000           48 2014-03-25      D
     41592474 27188     10024  2127214900           75 2014-02-03      D
     41592433 32638     10018  2122169421            3 2014-06-30      D
     41591881 27155     10003  6462178815            3 2013-09-19      D
     41591834 27154     10003  2127778424           82 2014-07-25      D
     41591831 33005     10032  2122837752           55 2013-10-16      D
     41591687 27224     10019  2122473936           48 2014-07-16      D
     41591587 27149     10016  2129730690            3 2014-01-13      D
     41591488 27138     10038  2123494433           48 2014-04-24      U
     41591211 32558     10065  2123552233           35 2014-07-28      D
     41591002 27104     10036  2127192300            3 2014-06-19      D
     41593270 26316     10036  6465903838            3 2013-08-15      D
     41590670 27099     10017  6464872003           17 2014-08-15      B
     41590509 32333     10017  2128670318           20 2013-11-26      D
     41590276 26232     10017  2128678889           69 2014-05-12      D
...                       ...         ...          ...        ...    ...
5    50013599 531589    10306  9649421836           99 1900-01-01    NaN
     50013641 531734    10309  9175414105           99 1900-01-01    NaN
     50013726 531492    10302  7184422332           99 1900-01-01    NaN
     50013753 531736    10310  3473070760           99 1900-01-01    NaN
     50013966 435864    10306  7186682562           70 2014-08-21      B
     50014024 531439    10309  7189666150           99 1900-01-01    NaN
     50014170 531500    10303  7185672314           99 1900-01-01    NaN
     50014387 531841    10304  7185560480           99 1900-01-01    NaN
     50014405 531757    10301  3475521679           99 1900-01-01    NaN
     50014447 531611    10309  6464201293           99 1900-01-01    NaN
     50014492 531508    10301  7186982370           99 1900-01-01    NaN
     50014518 531903    10310  9178373872           99 1900-01-01    NaN
     50014530 531904    10306  7189801189           99 1900-01-01    NaN
     50014537 531905    10314  7187204900           99 1900-01-01    NaN
     50014588 531851    10312  7186053663           99 1900-01-01    NaN
     50014605 531764    10301  7182372050           99 1900-01-01    NaN
     50014650 531457    10305  7184427248           99 1900-01-01    NaN
     50014668 531783    10302  9177701113           99 1900-01-01    NaN
     50014670 531460    10310  9173787516           99 1900-01-01    NaN
     50014732 531915    10304  3476068825           99 1900-01-01    NaN
     50014761 531664    10306  2014248581           99 1900-01-01    NaN
     50014828 531465    11419  7188441560           99 1900-01-01    NaN
     50014874 531792    10305  7183515000           99 1900-01-01    NaN
     50014885 531768    10312  7186199896           99 1900-01-01    NaN
     50014920 531927    10306  7189805300           99 1900-01-01    NaN
     50014935 531835    10301  7187206568           99 1900-01-01    NaN
     50014978 531521    10305  7187179885           99 1900-01-01    NaN
     50015012 531810    10305     9877000           99 1900-01-01    NaN
     50015034 531674    10309  7186059335           99 1900-01-01    NaN
     50015047 531524    10312  7182271570           99 1900-01-01    NaN

                     VIOLCODE  SCORE CURRENTGRADE  GRADEDATE  \
BORO
0    40959339 8214        10B     12            A 2013-09-10
     41289266 17965       04H     11            A 2014-02-20
     41669940 30637       10F      5            A 2014-08-21
     41722563 33950       09C     11            A 2014-04-18
     50003253 46262       02G      7            A 2014-02-21
     50003719 38434       06D      8            A 2014-08-11
     50009623 40128       04N     11            A 2014-06-23
     50009993 48116       10F      8            A 2014-05-20
     50011108 38013       10B      3            A 2014-07-28
     50010945 433431      10F     19            N        NaT
     50003629 36150       06C     21            Z 2014-03-25
     50013521 531641      NaN    NaN          NaN        NaT
1    30191841 2           10B     11            A 2013-07-22
     41593113 27279       06C      7            A 2014-02-11
     41592830 27189       02G      8            A 2014-08-08
     41592502 32639       10F      7            A 2014-03-25
     41592474 27188       10F      5            A 2014-02-03
     41592433 32638       10F      2            A 2014-06-30
     41591881 27155       10H     12            A 2013-09-19
     41591834 27154       08A     11            A 2014-07-25
     41591831 33005       06A      5            A 2013-10-16
     41591687 27224       10F     12            A 2014-07-16
     41591587 27149       02G      7            A 2014-01-13
     41591488 27138       08A     12            A 2014-04-24
     41591211 32558       10F      9            A 2014-07-28
     41591002 27104       06D     10            A 2014-06-19
     41593270 26316       10A      9            A 2013-08-15
     41590670 27099       NaN      0            A 2014-08-15
     41590509 32333       06D     13            A 2013-11-26
     41590276 26232       06D     12            A 2014-05-12
...                       ...    ...          ...        ...
5    50013599 531589      NaN    NaN          NaN        NaT
     50013641 531734      NaN    NaN          NaN        NaT
     50013726 531492      NaN    NaN          NaN        NaT
     50013753 531736      NaN    NaN          NaN        NaT
     50013966 435864      NaN      0          NaN        NaT
     50014024 531439      NaN    NaN          NaN        NaT
     50014170 531500      NaN    NaN          NaN        NaT
     50014387 531841      NaN    NaN          NaN        NaT
     50014405 531757      NaN    NaN          NaN        NaT
     50014447 531611      NaN    NaN          NaN        NaT
     50014492 531508      NaN    NaN          NaN        NaT
     50014518 531903      NaN    NaN          NaN        NaT
     50014530 531904      NaN    NaN          NaN        NaT
     50014537 531905      NaN    NaN          NaN        NaT
     50014588 531851      NaN    NaN          NaN        NaT
     50014605 531764      NaN    NaN          NaN        NaT
     50014650 531457      NaN    NaN          NaN        NaT
     50014668 531783      NaN    NaN          NaN        NaT
     50014670 531460      NaN    NaN          NaN        NaT
     50014732 531915      NaN    NaN          NaN        NaT
     50014761 531664      NaN    NaN          NaN        NaT
     50014828 531465      NaN    NaN          NaN        NaT
     50014874 531792      NaN    NaN          NaN        NaT
     50014885 531768      NaN    NaN          NaN        NaT
     50014920 531927      NaN    NaN          NaN        NaT
     50014935 531835      NaN    NaN          NaN        NaT
     50014978 531521      NaN    NaN          NaN        NaT
     50015012 531810      NaN    NaN          NaN        NaT
     50015034 531674      NaN    NaN          NaN        NaT
     50015047 531524      NaN    NaN          NaN        NaT

                                  RECORDDATE  SD  SE
BORO
0    40959339 8214   2014-09-04 06:01:28.403  12  12
     41289266 17965  2014-09-04 06:01:28.403  11  11
     41669940 30637  2014-09-04 06:01:28.403   5   5
     41722563 33950  2014-09-04 06:01:28.403  11  11
     50003253 46262  2014-09-04 06:01:28.403   7   7
     50003719 38434  2014-09-04 06:01:28.403   8   8
     50009623 40128  2014-09-04 06:01:28.403  11  11
     50009993 48116  2014-09-04 06:01:28.403   8   8

In [55]:
#BY cuisine
#c=df.groupby("CAMIS").apply(lambda x: x.sort_values(by='INSPDATE',ascending=False).head(1))
df=pd.read_csv("WebExtract.txt")

df['REPORTS'] = df['SE'] = df.SCORE
df=df[df.BORO!=0]
df.shape

(498315, 17)

In [56]:
c=df.groupby("CUISINECODE").agg({"REPORTS":pd.Series.count})
valid_cuisine=list(c[c.REPORTS>=100].index)
c
#c=df.groupby("CAMIS").apply(lambda x: x.sort_values(by='INSPDATE',ascending=False).head(1))
#c["REPROTS"]=df.SCORE
#cuisine=df.groupby('CUISINECODE').agg({"CAMIS":lambda x: x.nunique(),"SCORE":pd.Series.mean,"SE":pd.Series.sem,})
#cuisine

             REPORTS
CUISINECODE
0                118
1                276
2               1788
3             119178
4                574
5               7337
6                233
7               3533
8              15507
9                779
10               775
11                35
12               988
13               631
14             14218
15               168
16                 2
17             15465
18              7034
19                 3
20             59264
21               424
22              1272
23               941
24               660
25                48
26               119
27              9216
28              1780
29              6082
...              ...
54              3925
55             17460
56              2996
57               263
58                60
59               787
60               396
61              1814
62             24594
63             10189
64               686
66               245
67              1884
68               539
69              6367
70              2964
71               144
72              3075
73               985
74                43
75               567
76               194
77             12491
78              1711
80               544
81              2708
82              6640
83              1467
84              1901
99              1767

[84 rows x 1 columns]

In [57]:
df.index=df.CUISINECODE
df=df.ix[valid_cuisine]
c=df.groupby("CUISINECODE").agg({"SCORE":pd.Series.mean,"SE":pd.Series.sem,"REPORTS":pd.Series.count})
c=c.sort_values(by='SCORE',ascending=True)
#c=c.reset_index()
c["CUISINECODE"]=c.index
#c=c[c.REPORTS>=100]
c
#c

                 SCORE  REPORTS        SE  CUISINECODE
CUISINECODE
42           14.519231      156  1.000392           42
75           14.961199      567  0.409407           75
33           15.346154      286  0.425202           33
29           15.536337     6082  0.143528           29
41           15.541387      447  0.439387           41
43           15.943380     3497  0.195220           43
69           16.440553     6367  0.145486           69
51           16.898990     2574  0.238327           51
14           17.131734    14218  0.103514           14
70           17.213900     2964  0.221504           70
15           17.214286      168  0.588609           15
4            17.233449      574  0.408657            4
99           17.392756     1767  0.365021           99
39           17.512352     7448  0.132405           39
12           17.851215      988  0.404277           12
31           18.541935      310  0.623017           31
32           18.644654      318  0.582728           32
76           19.211340      194  0.689035           76
18           19.317600     7034  0.153411           18
71           20.083333      144  0.822216           71
68           20.168831      539  0.600517           68
56           20.265354     2996  0.273593           56
37           20.570352      796  0.374512           37
38           20.713700     2438  0.275221           38
26           20.739496      119  1.146290           26
47           20.830140     4227  0.203190           47
10           20.859355      775  0.454479           10
84           20.871647     1901  0.343706           84
81           20.915805     2708  0.288884           81
60           21.005051      396  0.688054           60
...                ...      ...       ...          ...
6            22.257511      233  1.124588            6
0            22.262712      118  1.815893            0
83           22.670075     1467  0.400467           83
50           22.675635     7285  0.173425           50
13           22.822504      631  0.510218           13
72           22.887154     3075  0.297206           72
30           23.064516     1395  0.399327           30
8            23.069646    15507  0.129861            8
17           23.092596    15465  0.126495           17
55           23.271306    17460  0.112691           55
77           23.452966    12491  0.139492           77
73           23.487310      985  0.455926           73
67           23.525478     1884  0.391793           67
82           23.557530     6640  0.176957           82
49           23.808591    17669  0.114477           49
28           24.450000     1780  0.372249           28
53           24.499556    24790  0.102777           53
27           24.519531     9216  0.162527           27
52           24.533454     6651  0.195302           52
61           24.865491     1814  0.397246           61
20           24.918939    59264  0.068170           20
44           25.093489     7894  0.202403           44
59           25.592122      787  0.641515           59
22           26.032233     1272  0.458124           22
5            26.062151     7337  0.215607            5
9            26.586650      779  0.654190            9
2            26.658837     1788  0.454865            2
66           26.685714      245  1.107902           66
21           27.424528      424  0.821818           21
24           30.145455      660  0.828039           24

[75 rows x 4 columns]

In [58]:
len(valid_cuisine)

75

In [59]:
cuisine_df=pd.read_csv("Cuisine.txt")
#cuisine_df
c_joined = c.merge(cuisine_df, on='CUISINECODE', how='left')
c_joined.REPORTS.sum()

497937.0

In [60]:
ans=[(row[1].CODEDESC,row[1].SCORE,row[1].SE,int(row[1].REPORTS)) for row in c_joined.iterrows()]
ans

[('Hotdogs/Pretzels', 14.51923076923077, 1.0003916170255034, 156),
 ('Soups & Sandwiches', 14.961199294532628, 0.4094073686199163, 567),
 ('Ethiopian', 15.346153846153847, 0.425201833030848, 286),
 ('Donuts', 15.536336731338375, 0.1435276456301111, 6082),
 ('Hotdogs', 15.5413870246085, 0.4393868291224805, 447),
 ('Ice Cream, Gelato, Yogurt, Ices',
  15.943380040034315,
  0.1952204514252206,
  3497),
 ('Sandwiches', 16.44055285063609, 0.14548557436527482, 6367),
 ('Juice, Smoothies, Fruit Salads',
  16.8989898989899,
  0.23832715850164432,
  2574),
 ('Caf\xe9/Coffee/Tea', 17.13173442115628, 0.1035143123602948, 14218),
 ('Sandwiches/Salads/Mixed Buffet',
  17.213900134952766,
  0.2215039631718001,
  2964),
 ('Cajun', 17.214285714285715, 0.5886086483756457, 168),
 ('Armenian', 17.233449477351915, 0.4086566464601228, 574),
 ('Other', 17.39275608375778, 0.3650210196871172, 1767),
 ('Hamburgers', 17.51235230934479, 0.13240450980730598, 7448),
 ('Bottled beverages, including water, sodas, juices, etc.',
  17.851214574898787,
  0.40427666581749316,
  988),
 ('Egyptian', 18.54193548387097, 0.6230174095024665, 310),
 ('English', 18.644654088050313, 0.5827276488437103, 318),
 ('Southwestern', 19.211340206185568, 0.6890354941307912, 194),
 ('Chicken', 19.317600227466592, 0.15341128851846414, 7034),
 ('Scandinavian', 20.083333333333332, 0.8222160534429129, 144),
 ('Salads', 20.16883116883117, 0.6005173848124247, 539),
 ('Middle Eastern', 20.26535380507343, 0.2735928807151001, 2996),
 ('German', 20.57035175879397, 0.3745124413929535, 796),
 ('Greek', 20.713699753896638, 0.27522126467540586, 2438),
 ('Czech', 20.73949579831933, 1.146290201297618, 119),
 ('Irish', 20.830139578897562, 0.20319008377102257, 4227),
 ('Barbecue', 20.859354838709677, 0.4544789183605483, 775),
 ('Vegetarian', 20.871646501841138, 0.34370646614899436, 1901),
 ('Tex-Mex', 20.915805022156572, 0.2888837252529678, 2708),
 ('Pancakes/Waffles', 21.005050505050505, 0.6880535276726528, 396),
 ('Moroccan', 21.041825095057035, 0.888989234694099, 263),
 ('Bagels/Pretzels', 21.06962921030286, 0.2334347691652179, 3533),
 ('Polish', 21.252186588921283, 0.45085183154561803, 686),
 ('American ', 21.354897716021412, 0.04171864738765694, 119178),
 ('Pizza', 21.370334227860454, 0.09176618080187732, 24594),
 ('Mediterranean', 21.586496815286623, 0.24783444765941337, 3925),
 ('Steak', 21.696084161309177, 0.38936685948790245, 1711),
 ('Filipino', 21.809963099630995, 0.5393487636887533, 542),
 ('Continental', 21.908607863974495, 0.4530531186418452, 941),
 ('Indonesian', 21.966666666666665, 0.8139360144690306, 210),
 ('French', 21.998288159771754, 0.17709974717651172, 7010),
 ('Afghan', 22.079710144927535, 0.8331112724698656, 276),
 ('Tapas', 22.09375, 0.6659220331660752, 544),
 ('Italian', 22.179524063951337, 0.09316033631826877, 24331),
 ('Pizza/Italian', 22.192953184807145, 0.13975090047795197, 10189),
 ('Australian', 22.257510729613735, 1.1245882063845891, 233),
 ('Not Listed/Not Applicable', 22.26271186440678, 1.8158934224350856, 118),
 ('Turkish', 22.67007498295842, 0.40046749630299205, 1467),
 ('Jewish/Kosher', 22.67563486616335, 0.1734253927074168, 7285),
 ('Brazilian', 22.822503961965136, 0.5102183790932573, 631),
 ('Seafood', 22.887154471544715, 0.2972057876192957, 3075),
 ('Eastern European', 23.06451612903226, 0.39932667906544395, 1395),
 ('Bakery', 23.069645966337784, 0.1298612080927805, 15507),
 ('Caribbean', 23.092596184933722, 0.1264947301406771, 15465),
 ('Mexican', 23.2713058419244, 0.11269101997013733, 17460),
 ('Spanish', 23.452966135617643, 0.13949166279520017, 12491),
 ('Soul Food', 23.487309644670052, 0.45592555815054175, 985),
 ('Russian', 23.52547770700637, 0.3917934495300716, 1884),
 ('Thai', 23.55753012048193, 0.17695725118993183, 6640),
 ('Japanese', 23.808591318127796, 0.11447723411350724, 17669),
 ('Vietnamese/Cambodian/Malaysia', 24.45, 0.37224907475227953, 1780),
 ('Latin (Cuban, Dominican, Puerto Rican, South & Central American)',
  24.4995562726906,
  0.10277746995947623,
  24790),
 ('Delicatessen', 24.51953125, 0.16252666679358346, 9216),
 ('Korean', 24.533453615997594, 0.1953023782484572, 6651),
 ('Peruvian', 24.865490628445425, 0.39724560212786353, 1814),
 ('Chinese', 24.91893898488121, 0.06817014785544305, 59264),
 ('Indian', 25.093488725614392, 0.20240346467056375, 7894),
 ('Pakistani', 25.592121982210926, 0.6415148865470436, 787),
 ('Chinese/Japanese', 26.032232704402517, 0.45812403038983845, 1272),
 ('Asian', 26.062150742810413, 0.2156066570743075, 7337),
 ('Bangladeshi', 26.586649550706035, 0.6541898062400494, 779),
 ('African', 26.658836689038033, 0.4548654080746964, 1788),
 ('Portuguese', 26.685714285714287, 1.1079022099407376, 245),
 ('Chinese/Cuban', 27.42452830188679, 0.8218178838154244, 424),
 ('Creole', 30.145454545454545, 0.8280390563340795, 660)]

In [575]:
pd.Series.sum(c_joined.REPORTS)

497937.0

In [292]:
cuisine_df=pd.read_csv("Cuisine.txt")
#violations_df=pd.read_csv("Violation.txt")
df=pd.read_csv("WebExtract.txt")
#df.INSPDATE=pd.to_datetime(df.INSPDATE)
#df=df[np.isfinite(df.VIOLCODE)]
c_joined = df.merge(cuisine_df, on='CUISINECODE', how='left')
#g=c_joined.merge()
#A=df.groupby(['CUISINECODE','VIOLCODE']).CAMIS.count()
#violations_df
#cuisine_df
c_joined

#x=A[0]
#x.index

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,CODEDESC
0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03 00:00:00,D,10F,2,A,2014-03-03 00:00:00,2014-09-04 06:01:28.403000000,Bakery
1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,06A,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000,Hamburgers
2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10B,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000,American
3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,08C,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000,Delicatessen
4,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,02G,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000,American
5,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10F,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000,American
6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10 00:00:00,D,10F,5,A,2014-06-10 00:00:00,2014-09-04 06:01:28.403000000,American
7,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,06D,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
8,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,04M,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000,Delicatessen
9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,10F,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000,"Ice Cream, Gelato, Yogurt, Ices"
10,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,10F,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000,Delicatessen
11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06A,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000,American
12,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,06C,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000,"Ice Cream, Gelato, Yogurt, Ices"
13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10I,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000,American
14,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,02G,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000,Hamburgers
15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,10H,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
16,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000,American
17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02 00:00:00,U,04C,19,Z,2014-09-02 00:00:00,2014-09-04 06:01:28.403000000,American
18,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,02B,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06D,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000,American
20,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10E,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000,American
21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07 00:00:00,D,10B,3,A,2014-05-07 00:00:00,2014-09-04 06:01:28.403000000,American
22,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2013-08-28 00:00:00,D,02B,7,A,2013-08-28 00:00:00,2014-09-04 06:01:28.403000000,Chinese
23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10 00:00:00,D,04L,13,A,2013-10-10 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
24,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,04J,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000,Hamburgers
25,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06A,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000,American
26,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06D,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
27,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06E,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000,Jewish/Kosher
28,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06D,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000,American
29,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,06F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000,American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531905,50014537,"1734 VICTORY BOULEVARD,INC.",5,1734,VICTORY BOULEVARD,10314,7187204900,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531906,50014563,FACEBOOK INC,1,770,BROADWAY,10003,6503675751,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531907,50014593,shinas pizza and grilling inc,4,88-38,SUTPHIN BOULEVARD ...,11435,3479655770,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531908,50014596,ALNINA CORP.,3,2474,OCEAN AVENUE,11229,9172021300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531909,50014597,Mian Noodle Bar,4,184-02,HORACE HARDING EXPRESSWAY,11365,5169677575,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531910,50014602,"NINETEEN TWENTY FOUR, INC",3,263,MOORE STREET ...,11206,7184171118,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531911,50014697,NEW JADE FOUNTAIN ENTERPRISES CORP,4,185-20,HORACE HARDING EXPRESSWAY,11365,7189399880,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531912,50014704,CREOLE 516 INC.,4,216-19,LINDEN BOULEVARD,11411,5164512071,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531913,50014705,JUICELAND PARK SLOPE INC,3,337,9 STREET,11215,7187881314,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531914,50014712,givers and takers,3,286,3 AVENUE ...,11215,9176271984,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531915,50014732,POPULAR CHICKEN INC,5,229,BROAD STREET,10304,3476068825,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531916,50014737,ZHONG ZHENG 26 RESTAURANT INC,1,26B,E BWAY ...,10002,2122199088,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531917,50014741,Q & Q BAKERY INC.,1,50,EAST BROADWAY,10002,2122262282,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531918,50014840,7 HUA JI PORT CHOP FAST FOOD INC,1,7,ALLEN STREET,10002,9179159663,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531919,50014853,MELT SHOP,1,877,8 AVENUE,10019,2125055861,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531920,50014866,IBM CAFETERIA,1,51,ASTOR PLACE,10003,8452341267,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531921,50014871,CIELO CAFE INC,4,147-36,NORTHERN BOULEVARD ...,11354,7188868871,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531922,50014875,MI RINCONCITO RESTAURANTE,2,131,EAST 169 STREET,10452,7186817474,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531923,50014882,MEANE JOE GREENE LLC,3,524,GRAND STREET ...,11211,9179165602,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531924,50014887,ZMA CORP,1,1159,3 AVENUE ...,10065,9176936031,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531925,50014889,SHARON'S ASIAN RESTAURANT INC,3,1232,AVENUE U,11229,9179578191,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531926,50014901,NUTELLERIA,3,82,5 AVENUE,11217,3473704444,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531927,50014920,FUSHIMI JAPANESE CUISINE,5,2110,RICHMOND ROAD,10306,7189805300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531928,50014921,Dunkin Donuts,1,542,EAST 14 STREET,10009,2125325003,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531929,50014955,Veinard Cafe Inc.,3,109,ORIENTAL BOULEVARD,11235,3478853050,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531930,50014960,PEPPA POT JAMAICAN CUISINE,4,134-28,GUY R BREWER BOULEVARD,11434,7185288200,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531931,50014972,BELLINI,1,483,COLUMBUS AVENUE,10024,2127244615,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other
531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000,Other

In [304]:
#c_joined=pd.DataFrame([c_joined.VIOLCODE,c_joined.CUISINECODE])
A=c_joined[['VIOLCODE','CODEDESC']]
#A=A.dropna()
cuisine_list=A.CODEDESC.unique()
violation_list=A.VIOLCODE.unique()
vv=A.groupby("VIOLCODE").count()
A
vv

          CODEDESC
VIOLCODE
02A            498
02B          24523
02C            550
02D             52
02E             19
02F             10
02G          45819
02H           3160
02I             42
03A            593
03B            331
03C            474
03D             90
03E             22
03G             20
04A           9264
04B             38
04C           4726
04D            496
04E            324
04F             89
04G             16
04H          15954
04I             25
04J           6272
04K           3306
04L          38306
04M          14568
04N          21508
04O            541
...            ...
10M              1
15E             11
15H              1
15I            453
15J            464
15K            391
15L           3128
15S            298
15T             90
16A            916
16B           5852
16C            188
16E             16
16F             10
18A             67
18B             29
18C             32
18D            137
18F             69
18G             38
20A            884
20B             18
20D           1945
20E            476
20F           3775
22A           1746
22B            396
22C           4401
22E             61
99B           2257

[97 rows x 1 columns]

In [305]:
D=A.groupby(['CODEDESC','VIOLCODE']).CODEDESC.count()
D

CODEDESC                       VIOLCODE
Afghan                         02B           4
                               02G          12
                               02H           1
                               04A           6
                               04C           3
                               04D           1
                               04F           1
                               04H           4
                               04I           1
                               04J           2
                               04K           4
                               04L          34
                               04M          11
                               04N          13
                               05D           2
                               05E           1
                               06A          12
                               06B           2
                               06C          16
                               06D          18
                               06E           8
                               06F           1
                               08A          36
                               08B           2
                               08C           5
                               09A           1
                               09B           3
                               09C           1
                               10A           2
                               10B          18
                                          ...
Vietnamese/Cambodian/Malaysia  06D         139
                               06E          56
                               06F          49
                               08A         165
                               08B           5
                               08C          20
                               09A          11
                               09B          31
                               09C          20
                               10A           5
                               10B         105
                               10D          21
                               10E           6
                               10F         199
                               10G           1
                               10H          22
                               10I          12
                               10J           2
                               15I           1
                               15L           7
                               16A           5
                               16B          13
                               18D           1
                               20A           3
                               20D           1
                               20E           2
                               20F           9
                               22B           1
                               22C           9
                               99B           9
Name: CODEDESC, dtype: int64

In [320]:
ans=[]
for c1 in cuisine_list:
    for v1 in violation_list:
        #print v1
        if v1 in D[c1].index:
            #print A[v1][c1]
            if D[c1][v1]>=100:
                count=float(D[c1][v1])
                s=float(D[c1].sum())
                p_cond=count/s
                p=vv.loc[v1][0]/float(vv.CODEDESC.sum())
                a=((c1,v1),p_cond/p,count)
                ans.append(a)
            #print D[v1][c1]
            #print p_cond
            #print v1,c1
g=sorted(ans, key=lambda x: -x[1])[:20]
g

[(('Bakery', '16A'), 3.5308796007485959, 100.0),
 (('Japanese', '04C'), 3.2441736633039722, 541.0),
 (('Caf\xe9/Coffee/Tea', '20D'), 3.1528542316115793, 175.0),
 (('Juice, Smoothies, Fruit Salads', '04A'), 3.0895762870547507, 145.0),
 (('Donuts', '10E'), 3.0373024983434593, 130.0),
 (('Ice Cream, Gelato, Yogurt, Ices', '04A'), 2.9559491371480471, 193.0),
 (('Thai', '09B'), 2.6329943302133367, 151.0),
 (('Irish', '04H'), 2.3693049675211078, 321.0),
 (('Mexican', '02H'), 2.3260790831701716, 260.0),
 (('Indian', '02H'), 2.2589839331918253, 112.0),
 (('Chinese', '09B'), 2.197103345855651, 1121.0),
 (('Caribbean', '02H'), 2.1084267631103071, 206.0),
 (('Hamburgers', '10E'), 2.0946895908706287, 109.0),
 (('Soups & Sandwiches', '02G'), 2.0914237422127164, 106.0),
 (('Chinese', '04D'), 2.0865716798779195, 121.0),
 (('American ', '15I'), 2.0798573716850686, 227.0),
 (('Donuts', '22C'), 2.0648964042362259, 110.0),
 (('Middle Eastern', '04A'), 1.9850440015702, 117.0),
 (('Spanish', '02H'), 1.9008790167390315, 151.0),
 (('Hamburgers', '04N'), 1.8956434541920506, 600.0)]

In [322]:
np.mean([i[1] for i in g])

2.4551316551328322

In [324]:
#pd.read_csv("Violation.csv")

IOError: File Violation.csv does not exist