In [102]:
import pandas as pd
import numpy as np

In [169]:
df=pd.read_csv("WebExtract.txt")

In [170]:
df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE
0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03 00:00:00,D,10F,2,A,2014-03-03 00:00:00,2014-09-04 06:01:28.403000000
1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,06A,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10B,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,08C,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
4,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,02G,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
5,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10F,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10 00:00:00,D,10F,5,A,2014-06-10 00:00:00,2014-09-04 06:01:28.403000000
7,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,06D,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000
8,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,04M,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,10F,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000
10,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,10F,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06A,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000
12,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,06C,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000
13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10I,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
14,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,02G,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,10H,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
16,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02 00:00:00,U,04C,19,Z,2014-09-02 00:00:00,2014-09-04 06:01:28.403000000
18,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,02B,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000
19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06D,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000
20,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10E,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07 00:00:00,D,10B,3,A,2014-05-07 00:00:00,2014-09-04 06:01:28.403000000
22,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2013-08-28 00:00:00,D,02B,7,A,2013-08-28 00:00:00,2014-09-04 06:01:28.403000000
23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10 00:00:00,D,04L,13,A,2013-10-10 00:00:00,2014-09-04 06:01:28.403000000
24,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,04J,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
25,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06A,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000
26,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06D,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
27,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06E,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
28,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06D,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000
29,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,06F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531905,50014537,"1734 VICTORY BOULEVARD,INC.",5,1734,VICTORY BOULEVARD,10314,7187204900,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531906,50014563,FACEBOOK INC,1,770,BROADWAY,10003,6503675751,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531907,50014593,shinas pizza and grilling inc,4,88-38,SUTPHIN BOULEVARD ...,11435,3479655770,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531908,50014596,ALNINA CORP.,3,2474,OCEAN AVENUE,11229,9172021300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531909,50014597,Mian Noodle Bar,4,184-02,HORACE HARDING EXPRESSWAY,11365,5169677575,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531910,50014602,"NINETEEN TWENTY FOUR, INC",3,263,MOORE STREET ...,11206,7184171118,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531911,50014697,NEW JADE FOUNTAIN ENTERPRISES CORP,4,185-20,HORACE HARDING EXPRESSWAY,11365,7189399880,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531912,50014704,CREOLE 516 INC.,4,216-19,LINDEN BOULEVARD,11411,5164512071,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531913,50014705,JUICELAND PARK SLOPE INC,3,337,9 STREET,11215,7187881314,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531914,50014712,givers and takers,3,286,3 AVENUE ...,11215,9176271984,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531915,50014732,POPULAR CHICKEN INC,5,229,BROAD STREET,10304,3476068825,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531916,50014737,ZHONG ZHENG 26 RESTAURANT INC,1,26B,E BWAY ...,10002,2122199088,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531917,50014741,Q & Q BAKERY INC.,1,50,EAST BROADWAY,10002,2122262282,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531918,50014840,7 HUA JI PORT CHOP FAST FOOD INC,1,7,ALLEN STREET,10002,9179159663,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531919,50014853,MELT SHOP,1,877,8 AVENUE,10019,2125055861,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531920,50014866,IBM CAFETERIA,1,51,ASTOR PLACE,10003,8452341267,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531921,50014871,CIELO CAFE INC,4,147-36,NORTHERN BOULEVARD ...,11354,7188868871,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531922,50014875,MI RINCONCITO RESTAURANTE,2,131,EAST 169 STREET,10452,7186817474,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531923,50014882,MEANE JOE GREENE LLC,3,524,GRAND STREET ...,11211,9179165602,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531924,50014887,ZMA CORP,1,1159,3 AVENUE ...,10065,9176936031,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531925,50014889,SHARON'S ASIAN RESTAURANT INC,3,1232,AVENUE U,11229,9179578191,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531926,50014901,NUTELLERIA,3,82,5 AVENUE,11217,3473704444,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531927,50014920,FUSHIMI JAPANESE CUISINE,5,2110,RICHMOND ROAD,10306,7189805300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531928,50014921,Dunkin Donuts,1,542,EAST 14 STREET,10009,2125325003,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531929,50014955,Veinard Cafe Inc.,3,109,ORIENTAL BOULEVARD,11235,3478853050,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531930,50014960,PEPPA POT JAMAICAN CUISINE,4,134-28,GUY R BREWER BOULEVARD,11434,7185288200,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531931,50014972,BELLINI,1,483,COLUMBUS AVENUE,10024,2127244615,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000

In [171]:
df['SD'] = df['SE'] = df.SCORE

In [345]:
df.INSPDATE=pd.to_datetime(df.INSPDATE)
df.GRADEDATE=pd.to_datetime(df.GRADEDATE)
df.RECORDDATE=pd.to_datetime(df.RECORDDATE)
c=df.groupby("CAMIS").apply(lambda x: x.sort_values(by='INSPDATE',ascending=False).head(1))
c

,,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,SD,SE
CAMIS,,,,,,,,,,,,,,,,,,
30075445,0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03,D,10F,2,A,2014-03-03,2014-09-04 06:01:28.403,2,2
30112340,1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,06A,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
30191841,2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10B,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
40356018,6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10,D,10F,5,A,2014-06-10,2014-09-04 06:01:28.403,5,5
40356068,56265,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2014-01-29,P,08A,12,NaN,NaT,2014-09-04 06:01:28.403,12,12
40356151,19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06D,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10
40356442,15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,10H,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
40356483,3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,08C,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
40356649,11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06A,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12
40356731,9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,10F,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12
40357217,13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10I,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
40357437,30,40357437,C & C CATERING SERVICE,3,7715,18 AVENUE,11214,7182322800,3,2014-04-16,D,06D,5,A,2014-04-16,2014-09-04 06:01:28.403,5,5
40358429,56373,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2014-08-08,F,08A,50,NaN,NaT,2014-09-04 06:01:28.403,50,50
40359480,21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07,D,10B,3,A,2014-05-07,2014-09-04 06:01:28.403,3,3
40359705,468838,40359705,NATHAN'S FAMOUS,3,1310,SURF AVENUE,11224,7183332202,41,2014-02-20,D,15L,NaN,NaN,NaT,2014-09-04 06:01:28.403,NaN,NaN
40360045,23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10,D,04L,13,A,2013-10-10,2014-09-04 06:01:28.403,13,13
40360076,43,40360076,CARVEL ICE CREAM,3,203,CHURCH AVENUE ...,11218,7184389501,43,2014-02-10,D,10F,2,A,2014-02-10,2014-09-04 06:01:28.403,2,2
40361322,33,40361322,CARVEL ICE CREAM,4,265-15,HILLSIDE AVENUE ...,11004,7183430392,43,2013-09-18,D,08A,10,A,2013-09-18,2014-09-04 06:01:28.403,10,10
40361390,36,40361390,NORDIC DELICACIES,3,6909,3 AVENUE,11209,7187481874,27,2014-08-21,D,10B,4,A,2014-08-21,2014-09-04 06:01:28.403,4,4
40361521,17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02,U,04C,19,Z,2014-09-02,2014-09-04 06:01:28.403,19,19
40361606,41,40361606,THE MOVABLE FEAST,3,284,PROSPECT PARK WEST,11215,7189652900,3,2013-11-14,D,10F,2,A,2013-11-14,2014-09-04 06:01:28.403,2,2
40361618,34,40361618,SAL'S DELI,4,129-08,20 AVENUE,11356,7186619498,27,2014-08-16,D,06C,12,A,2014-08-16,2014-09-04 06:01:28.403,12,12
40361708,38,40361708,BULLY'S DELI,1,759,BROADWAY ...,10003,2122549755,27,2014-01-21,D,06D,12,A,2014-01-21,2014-09-04 06:01:28.403,12,12
40361998,48985,40361998,STEVE CHU'S DELI & GROCERY,4,3406,10 STREET ...,11106,7187268888,27,2014-03-19,D,10F,3,A,2014-03-19,2014-09-04 06:01:28.403,3,3
40362098,47,40362098,HARRIET'S KITCHEN,1,502,AMSTERDAM AVENUE ...,10024,2127210045,18,2014-03-04,U,04N,13,A,2014-03-04,2014-09-04 06:01:28.403,13,13
40362264,56701,40362264,P & S DELI GROCERY,1,730,COLUMBUS AVENUE,10025,2129323030,3,2014-08-18,P,04L,24,NaN,NaT,2014-09-04 06:01:28.403,24,24
40362274,68,40362274,ANGELIKA FILM CENTER,1,18,WEST HOUSTON STREET,10012,2129952570,3,2014-04-03,D,06D,9,A,2014-04-03,2014-09-04 06:01:28.403,9,9
40362344,50,40362344,WHITE CASTLE,3,531,MYRTLE AVENUE,11205,7188578132,39,2014-03-18,D,06D,8,A,2014-03-18,2014-09-04 06:01:28.403,8,8
40362432,63,40362432,HO MEI RESTAURANT,4,103-05,37 AVENUE,11368,7187796903,20,2014-04-21,D,06C,10,A,2014-04-21,2014-09-04 06:01:28.403,10,10
40362715,52,40362715,THE COUNTRY CAFE,1,60,WALL STREET,10005,3474279132,83,2013-09-18,D,06B,13,A,2013-09-18,2014-09-04 06:01:28.403,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50014977,531808,50014977,ASMA ASLAM,4,236-03,BRADDOCK AVENUE,11426,3474979749,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014978,531521,50014978,CARAVAN BAZAR INC,5,1101,HYLAN BOULEVARD ...,10305,7187179885,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014979,531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014981,531797,50014981,673 9TH AVENUE,1,673,9 AVENUE ...,10036,2122036161,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014982,531798,50014982,NEW SUN CAFE JAPANESE CUISINE INC,1,67,READE STREET,10007,2126083822,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014986,531773,50014986,LITTLE CAESARS,3,8622,4 AVENUE,11209,8626626222,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014990,531522,50014990,POINT NYC INC,4,41-18,162 STREET,11358,7186613131,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014991,531862,50014991,"SULTAN'S PIZZA, INC.",3,666,FLATBUSH AVENUE ...,11225,3479337523,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014994,531799,50014994,POD 39 F&B LLC,1,145,EAST 39 STREET,10016,2128655700,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014995,531863,50014995,cloud social,1,6,WEST 32 STREET,10001,2129041092,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014997,531809,50014997,Lolo's Seafood Shack,1,303,WEST 116 STREET,10026,6465418940,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014998,531673,50014998,SNV NY INC,3,222,7 AVENUE,11215,7184994165,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015004,531800,50015004,BAGEL BOB,3,2114,FLATBUSH AVENUE,11234,7186854576,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015008,531774,50015008,LOMAZOYATL DELI GROCERY INC.,4,106-16,CORONA AVENUE,11368,NaN,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015009,531864,50015009,GREEN JUICE CAFE INC,1,4316,BROADWAY,10033,9176574635,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015011,531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015012,531810,50015012,NY FAMILY PIZZA,5,1880,HYLAN BOULEVARD,10305,9877000,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015019,531775,50015019,MBJ DOWNTOWN INC,1,199,CHAMBERS STREET,10013,2125874330,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015023,531836,50015023,URBAN CRAVE,1,42,BROADWAY,10004,7037237264,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015032,531776,50015032,AREPAS & CREPES COLOMBIAN CUISINE INC.,3,241,BAY RIDGE AVENUE ...,11220,6466109918,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015034,531674,50015034,EGGERS ICE CREAM PARLOR,5,6319,AMBOY ROAD,10309,7186059335,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015035,531801,50015035,AUNTIE ANNE'S,4,80-00,COOPER AVENUE ...,11385,5164588020,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015037,531777,50015037,SUBWAY LIBERTY 1148 LLC,3,1148,LIBERTY AVENUE ...,11208,NaN,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015038,531811,50015038,HONG DA RESTAURANT INC,1,42,BROADWAY,10004,9178368798,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015040,531523,50015040,FOREST POINT LLC,3,970,FLUSHING AVENUE,11206,7183662742,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015041,531778,50015041,"WHISPERS BAR, LOUNGE & RESTAURANT, LLC",1,210,WEST 94 STREET ...,10025,8453132814,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015042,531779,50015042,650 FOOD INC,3,650,MANHATTAN AVENUE,11222,7183833334,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015043,531865,50015043,TUMDRI INC,3,595,WASHINGTON AVENUE,11238,3474972856,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015047,531524,50015047,Parkside Pizza Corp,5,1547,ARTHUR KILL ROAD ...,10312,7182271570,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015048,531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN

In [338]:
df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,SD,SE
0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03,D,10F,2,A,2014-03-03,2014-09-04 06:01:28.403,2,2
1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,06A,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10B,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,08C,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
4,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,02G,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
5,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10F,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10,D,10F,5,A,2014-06-10,2014-09-04 06:01:28.403,5,5
7,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17,D,06D,13,Z,2013-01-17,2014-09-04 06:01:28.403,13,13
8,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,04M,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,10F,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12
10,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,10F,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06A,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12
12,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,06C,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12
13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10I,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
14,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,02G,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,10H,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
16,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10F,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02,U,04C,19,Z,2014-09-02,2014-09-04 06:01:28.403,19,19
18,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17,D,02B,13,Z,2013-01-17,2014-09-04 06:01:28.403,13,13
19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06D,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10
20,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10E,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07,D,10B,3,A,2014-05-07,2014-09-04 06:01:28.403,3,3
22,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2013-08-28,D,02B,7,A,2013-08-28,2014-09-04 06:01:28.403,7,7
23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10,D,04L,13,A,2013-10-10,2014-09-04 06:01:28.403,13,13
24,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,04J,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
25,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06A,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10
26,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,06D,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
27,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,06E,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
28,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06D,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12
29,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,06F,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531905,50014537,"1734 VICTORY BOULEVARD,INC.",5,1734,VICTORY BOULEVARD,10314,7187204900,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531906,50014563,FACEBOOK INC,1,770,BROADWAY,10003,6503675751,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531907,50014593,shinas pizza and grilling inc,4,88-38,SUTPHIN BOULEVARD ...,11435,3479655770,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531908,50014596,ALNINA CORP.,3,2474,OCEAN AVENUE,11229,9172021300,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531909,50014597,Mian Noodle Bar,4,184-02,HORACE HARDING EXPRESSWAY,11365,5169677575,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531910,50014602,"NINETEEN TWENTY FOUR, INC",3,263,MOORE STREET ...,11206,7184171118,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531911,50014697,NEW JADE FOUNTAIN ENTERPRISES CORP,4,185-20,HORACE HARDING EXPRESSWAY,11365,7189399880,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531912,50014704,CREOLE 516 INC.,4,216-19,LINDEN BOULEVARD,11411,5164512071,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531913,50014705,JUICELAND PARK SLOPE INC,3,337,9 STREET,11215,7187881314,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531914,50014712,givers and takers,3,286,3 AVENUE ...,11215,9176271984,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531915,50014732,POPULAR CHICKEN INC,5,229,BROAD STREET,10304,3476068825,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531916,50014737,ZHONG ZHENG 26 RESTAURANT INC,1,26B,E BWAY ...,10002,2122199088,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531917,50014741,Q & Q BAKERY INC.,1,50,EAST BROADWAY,10002,2122262282,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531918,50014840,7 HUA JI PORT CHOP FAST FOOD INC,1,7,ALLEN STREET,10002,9179159663,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531919,50014853,MELT SHOP,1,877,8 AVENUE,10019,2125055861,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531920,50014866,IBM CAFETERIA,1,51,ASTOR PLACE,10003,8452341267,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531921,50014871,CIELO CAFE INC,4,147-36,NORTHERN BOULEVARD ...,11354,7188868871,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531922,50014875,MI RINCONCITO RESTAURANTE,2,131,EAST 169 STREET,10452,7186817474,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531923,50014882,MEANE JOE GREENE LLC,3,524,GRAND STREET ...,11211,9179165602,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531924,50014887,ZMA CORP,1,1159,3 AVENUE ...,10065,9176936031,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531925,50014889,SHARON'S ASIAN RESTAURANT INC,3,1232,AVENUE U,11229,9179578191,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531926,50014901,NUTELLERIA,3,82,5 AVENUE,11217,3473704444,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531927,50014920,FUSHIMI JAPANESE CUISINE,5,2110,RICHMOND ROAD,10306,7189805300,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531928,50014921,Dunkin Donuts,1,542,EAST 14 STREET,10009,2125325003,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531929,50014955,Veinard Cafe Inc.,3,109,ORIENTAL BOULEVARD,11235,3478853050,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531930,50014960,PEPPA POT JAMAICAN CUISINE,4,134-28,GUY R BREWER BOULEVARD,11434,7185288200,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531931,50014972,BELLINI,1,483,COLUMBUS AVENUE,10024,2127244615,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN

In [334]:
c[df['BORO'] == 2]

KeyError: 'Columns not found: False, True'

In [314]:
type(df.GRADEDATE[0])

str

In [288]:
#Dataframe sorted by 
def SE(x):
    n=np.sqrt(x.count())
    if n==0:
        return None
    ans=np.std(x)
    return(ans)
a=df.groupby('ZIPCODE').agg({"CAMIS":lambda x: x.nunique(),"SCORE":np.mean,"SD":np.std,"SE":SE})
a
#b=a.CAMIS.nunique().sort_values(ascending=False).head(100)

             SCORE  CAMIS         SE         SD
ZIPCODE
7005     16.166667      1   4.579544   4.783178
10000    33.280000      1  32.985476  33.665660
10001    20.861558    509  15.030757  15.031627
10002    24.277107    474  16.958575  16.959450
10003    22.491749    675  15.044511  15.045051
10004    20.437790    142  13.814240  13.817154
10005    21.377374     69  15.231290  15.237582
10006    22.255633     47  13.507030  13.512886
10007    21.559110    139  14.486985  14.489812
10009    21.997789    312  14.677895  14.678977
10010    22.672749    246  16.064649  16.066278
10011    21.360411    463  13.679330  13.680077
10012    21.120305    402  13.034035  13.034824
10013    23.894068    480  16.101864  16.102570
10014    21.526370    408  13.843233  13.844032
10016    22.781260    414  14.714143  14.714941
10017    22.425101    376  14.811273  14.812240
10018    22.976900    333  15.433238  15.434338
10019    21.433635    660  14.331010  14.331594
10020    17.607703     48  12.457696  12.466591
10021    22.658479    152  15.654167  15.656484
10022    21.987891    488  15.428606  15.429391
10023    21.917738    197  15.013153  15.015083
10024    22.281986    202  14.945491  14.947233
10025    23.335293    237  15.353623  15.355128
10026    24.323741     74  16.035534  16.041305
10027    22.778005    163  15.895252  15.897968
10028    21.348417    214  13.733814  13.735424
10029    23.620480    197  17.266286  17.268565
10030    21.376910     39  15.648100  15.661401
...            ...    ...        ...        ...
11411    25.977358     23  17.067001  17.083124
11412    20.795580     45  13.565258  13.574636
11413    22.726154     41  16.892932  16.905942
11414    22.318267     50  14.785995  14.792961
11415    22.148794     36  16.808753  16.820030
11416    23.294912     44  17.420111  17.429163
11417    21.113982     69  14.128129  14.133500
11418    22.668075     88  15.609860  15.614573
11419    24.146455     91  17.294934  17.298969
11420    22.581787     87  16.388013  16.392768
11421    21.372155     73  12.893994  12.898311
11422    22.754902     41  14.834090  14.843188
11423    22.848821     35  16.680173  16.691753
11426    20.653782     30  14.699836  14.712204
11427    20.649596     19  16.573974  16.596356
11428    25.256769     40  15.931801  15.938763
11429    19.926641     24  12.484370  12.496438
11430    19.585848    148  13.606578  13.610311
11432    22.372653    188  16.236026  16.238174
11433    18.104202     30   9.596528   9.604602
11434    22.213096     90  15.235316  15.239693
11435    21.604319    106  13.769330  13.772137
11436    23.350174     23  15.300624  15.313969
11451     9.090909      1   4.399474   4.614207
11691    24.753636     45  14.867854  14.874217
11692    19.396947      9  11.206377  11.249396
11693    23.781857     28  15.762339  15.779389
11694    22.871915     38  13.523059  13.531012
11697    31.011628      3  15.702536  15.794634
11753    11.583333      1   2.325881   2.429303

[208 rows x 4 columns]

In [292]:
topzipcodes=a[a.CAMIS>100].sort_values('SCORE',ascending=False)
topzipcodes["ZIPCODE"]=topzipcodes.index
topzipcodes.shape
topzipcodes.head(5)
#topzipcodes[1]

#a=pd.DataFrame({a:topzipcodes.ZIPCODE,b:topzipcodes.SD})
topzipcodes= topzipcodes[['ZIPCODE', 'SCORE', 'SE', 'CAMIS']]
topzipcodes.ZIPCODE=topzipcodes.ZIPCODE.apply(int)
#topzipcodes.CAMIS.apply(int)
topzipcodes.CAMIS=topzipcodes.CAMIS.apply(int)
topzipcodes

         ZIPCODE      SCORE         SE  CAMIS
ZIPCODE
11354      11354  26.462010  19.194790    361
11220      11220  25.863225  17.358547    317
11355      11355  24.814897  15.795981    197
11373      11373  24.466033  16.146662    225
11226      11226  24.339778  17.390255    201
10002      10002  24.277107  16.958575    474
11372      11372  24.170565  17.029921    319
11230      11230  24.021692  16.183317    102
10013      10013  23.894068  16.101864    480
11218      11218  23.808065  16.113036    147
11214      11214  23.739612  16.000495    180
10032      10032  23.731100  17.158520    117
10029      10029  23.620480  17.266286    197
11368      11368  23.540505  16.160040    290
10025      10025  23.335293  15.353623    237
11235      11235  23.254341  16.974535    176
11216      11216  23.236073  15.723895    166
10128      10128  23.185958  15.799877    159
10018      10018  22.976900  15.433238    333
11208      11208  22.868733  14.935990    116
10016      10016  22.781260  14.714143    414
10027      10027  22.778005  15.895252    163
11104      11104  22.714286  14.644184    114
10010      10010  22.672749  16.064649    246
10021      10021  22.658479  15.654167    152
11221      11221  22.510137  17.650955    111
10003      10003  22.491749  15.044511    675
10017      10017  22.425101  14.811273    376
10036      10036  22.423251  15.446534    593
11204      11204  22.407027  15.234933    123
...          ...        ...        ...    ...
10014      10014  21.526370  13.843233    408
10019      10019  21.433635  14.331010    660
11215      11215  21.415858  14.224077    372
10011      10011  21.360411  13.679330    463
11231      11231  21.352941  14.532862    159
10028      10028  21.348417  13.733814    214
11237      11237  21.287353  13.337419    179
10463      10463  21.242828  14.174341    128
11225      11225  21.174666  13.712163    101
10012      10012  21.120305  13.034035    402
10314      10314  21.104534  13.255806    185
11211      11211  21.099701  14.070921    365
10461      10461  21.027596  15.477394    154
10467      10467  21.025978  14.718820    169
10462      10462  21.021255  15.371443    148
10001      10001  20.861558  15.030757    509
11375      11375  20.778711  12.393560    196
10472      10472  20.658988  14.052637    108
11209      11209  20.643797  14.120116    264
11217      11217  20.602597  13.917400    254
11369      11369  20.591995  14.218729    104
10301      10301  20.581284  12.473938    103
11207      11207  20.471055  12.553618    136
10004      10004  20.437790  13.814240    142
11249      11249  20.428417  11.936348    155
10065      10065  20.401325  12.256623    173
11361      11361  19.958353  13.299787    119
11430      11430  19.585848  13.606578    148
10306      10306  19.015512  12.014017    111
11234      11234  18.945892  12.787044    152

[92 rows x 4 columns]

In [305]:
l=[]
for i in range (len(topzipcodes)):
    t=tuple(topzipcodes.iloc[i])
    l.append(t)

for i in range (len(l)):
    x=list(l[i])
    zipcode=str(int(x[0]))
    camis=int(x[3])
    x[0]=zipcode
    x[3]=camis
    l[i]=tuple(x)
l

[('11354', 26.462010098581391, 19.19478962971375, 361),
 ('11220', 25.863225468361065, 17.358547397287325, 317),
 ('11355', 24.814897413024084, 15.795981015666086, 197),
 ('11373', 24.466032608695652, 16.146661720790608, 225),
 ('11226', 24.339778354161755, 17.3902553390481, 201),
 ('10002', 24.277107190756215, 16.958575494133441, 474),
 ('11372', 24.170565045992117, 17.029921131384519, 319),
 ('11230', 24.021691973969631, 16.183316915206365, 102),
 ('10013', 23.894068167878736, 16.10186438463758, 480),
 ('11218', 23.80806502031885, 16.11303608354023, 147),
 ('11214', 23.739612188365651, 16.00049545161777, 180),
 ('10032', 23.731099656357387, 17.158519924726967, 117),
 ('10029', 23.620480337820005, 17.266286146677828, 197),
 ('11368', 23.540504867183632, 16.160039942747151, 290),
 ('10025', 23.335292964922594, 15.353623271004114, 237),
 ('11235', 23.254340542187023, 16.974534560024857, 176),
 ('11216', 23.236073471845831, 15.723894769627329, 166),
 ('10128', 23.185957696827263, 15.799876622496351, 159),
 ('10018', 22.9769000427777, 15.433238040640351, 333),
 ('11208', 22.868733256792957, 14.935990169292067, 116),
 ('10016', 22.781260167010085, 14.714142767109484, 414),
 ('10027', 22.778005464480874, 15.895252491216837, 163),
 ('11104', 22.714285714285715, 14.644184419144388, 114),
 ('10010', 22.672749391727493, 16.06464925546717, 246),
 ('10021', 22.658478839893458, 15.654166860458242, 152),
 ('11221', 22.510136986301369, 17.65095460906781, 111),
 ('10003', 22.491749174917491, 15.044511255719096, 675),
 ('10017', 22.425101214574898, 14.811273214290518, 376),
 ('10036', 22.423251351822781, 15.446533887547693, 593),
 ('11204', 22.407027240426373, 15.234932884334555, 123),
 ('11106', 22.398936170212767, 15.349295177556025, 156),
 ('10451', 22.392642377078175, 16.38798431942045, 157),
 ('11236', 22.383215369059656, 16.291386167883587, 111),
 ('11432', 22.372652737371066, 16.236026338191284, 188),
 ('11222', 22.337138084632517, 14.87244134738031, 193),
 ('10034', 22.320117474302496, 13.345600875833796, 106),
 ('11229', 22.286210489753387, 14.88483242721929, 142),
 ('10024', 22.281985551153578, 14.945490933733687, 202),
 ('11232', 22.130981150314163, 15.441802123827648, 106),
 ('11219', 22.128552097428958, 14.509424287939495, 105),
 ('10033', 22.113469387755103, 13.983320319116753, 120),
 ('10468', 22.104070305272895, 17.731755801982583, 107),
 ('11377', 22.060877555708707, 14.074470205525184, 214),
 ('10458', 22.013929815162069, 14.734122572271291, 196),
 ('10009', 21.99778891509434, 14.677894625250955, 312),
 ('11385', 21.996373161394317, 15.886890738710418, 252),
 ('10022', 21.987890505749466, 15.428605913316668, 488),
 ('11358', 21.962829303500541, 14.317949247954527, 143),
 ('11223', 21.928736295441432, 16.139980195859227, 185),
 ('10023', 21.917737789203084, 15.013153411096805, 197),
 ('11201', 21.906092871931381, 14.75464007933445, 345),
 ('10038', 21.898205546492658, 14.79903704960558, 168),
 ('11101', 21.856084867894314, 14.195164922245121, 250),
 ('11238', 21.771921531552824, 14.846754452349634, 246),
 ('11203', 21.713423295454547, 14.822454611980737, 141),
 ('11205', 21.702141680395385, 14.233782772666762, 145),
 ('11105', 21.687824351297404, 14.119561870053928, 123),
 ('10452', 21.666361136571954, 14.670738675499456, 101),
 ('11206', 21.617133576938691, 14.753708934007086, 154),
 ('11435', 21.604319478402608, 13.769330254944615, 106),
 ('11103', 21.559838750314942, 15.052239916524449, 209),
 ('10007', 21.559110417479516, 14.486984683944213, 139),
 ('10014', 21.526370455856895, 13.843233349241681, 408),
 ('10019', 21.433634808115375, 14.33100963529945, 660),
 ('11215', 21.415857605177994, 14.22407696761341, 372),
 ('10011', 21.360410525166504, 13.679329739026363, 463),
 ('11231', 21.352941176470587, 14.532861706144104, 159),
 ('10028', 21.348417350527551, 13.733813892609733, 214),
 ('11237', 21.287352758834469, 13.337418799500934, 179),
 ('10463', 21.242828282828281, 14.174341025810273, 128),
 ('11225', 21.174666006927264, 13.712163413634418, 101),
 ('10012', 21.120305306518052, 13.03403466728926, 402),
 ('10314', 21.104534005037785, 13.255806373684043, 185),
 ('11211', 21.099701046337817, 14.070920619686394, 365),
 ('10461', 21.027596223674657, 15.477393530213909, 154),
 ('10467', 21.025978191148173, 14.718819532073192, 169),
 ('10462', 21.021255060728745, 15.371443072220924, 148),
 ('10001', 20.861558050700314, 15.030756843299605, 509),
 ('11375', 20.778710792788342, 12.393559908648955, 196),
 ('10472', 20.658988482724087, 14.052636780301626, 108),
 ('11209', 20.643796802266749, 14.120115899523661, 264),
 ('11217', 20.602597402597404, 13.917399873091394, 254),
 ('11369', 20.591995221027478, 14.218728557003782, 104),
 ('10301', 20.581283743251351, 12.473937702558601, 103),
 ('11207', 20.471054718477397, 12.553618341470401, 136),
 ('10004', 20.437789962041332, 13.814239898174643, 142),
 ('11249', 20.428416877028489, 11.936347601667306, 155),
 ('10065', 20.401324868893184, 12.256622961270615, 173),
 ('11361', 19.9583532790809, 13.299787044931854, 119),
 ('11430', 19.585847504114099, 13.606577635301178, 148),
 ('10306', 19.015512465373963, 12.01401687482922, 111),
 ('11234', 18.945891783567134, 12.78704403474887, 152)]

In [301]:
l[1]=l[0]
l

[(11354.0, 26.462010098581391, 19.19478962971375, 361.0),
 (11354.0, 26.462010098581391, 19.19478962971375, 361.0),
 (11355.0, 24.814897413024084, 15.795981015666086, 197.0),
 (11373.0, 24.466032608695652, 16.146661720790608, 225.0),
 (11226.0, 24.339778354161755, 17.3902553390481, 201.0),
 (10002.0, 24.277107190756215, 16.958575494133441, 474.0),
 (11372.0, 24.170565045992117, 17.029921131384519, 319.0),
 (11230.0, 24.021691973969631, 16.183316915206365, 102.0),
 (10013.0, 23.894068167878736, 16.10186438463758, 480.0),
 (11218.0, 23.80806502031885, 16.11303608354023, 147.0),
 (11214.0, 23.739612188365651, 16.00049545161777, 180.0),
 (10032.0, 23.731099656357387, 17.158519924726967, 117.0),
 (10029.0, 23.620480337820005, 17.266286146677828, 197.0),
 (11368.0, 23.540504867183632, 16.160039942747151, 290.0),
 (10025.0, 23.335292964922594, 15.353623271004114, 237.0),
 (11235.0, 23.254340542187023, 16.974534560024857, 176.0),
 (11216.0, 23.236073471845831, 15.723894769627329, 166.0),
 (10128.0, 23.185957696827263, 15.799876622496351, 159.0),
 (10018.0, 22.9769000427777, 15.433238040640351, 333.0),
 (11208.0, 22.868733256792957, 14.935990169292067, 116.0),
 (10016.0, 22.781260167010085, 14.714142767109484, 414.0),
 (10027.0, 22.778005464480874, 15.895252491216837, 163.0),
 (11104.0, 22.714285714285715, 14.644184419144388, 114.0),
 (10010.0, 22.672749391727493, 16.06464925546717, 246.0),
 (10021.0, 22.658478839893458, 15.654166860458242, 152.0),
 (11221.0, 22.510136986301369, 17.65095460906781, 111.0),
 (10003.0, 22.491749174917491, 15.044511255719096, 675.0),
 (10017.0, 22.425101214574898, 14.811273214290518, 376.0),
 (10036.0, 22.423251351822781, 15.446533887547693, 593.0),
 (11204.0, 22.407027240426373, 15.234932884334555, 123.0),
 (11106.0, 22.398936170212767, 15.349295177556025, 156.0),
 (10451.0, 22.392642377078175, 16.38798431942045, 157.0),
 (11236.0, 22.383215369059656, 16.291386167883587, 111.0),
 (11432.0, 22.372652737371066, 16.236026338191284, 188.0),
 (11222.0, 22.337138084632517, 14.87244134738031, 193.0),
 (10034.0, 22.320117474302496, 13.345600875833796, 106.0),
 (11229.0, 22.286210489753387, 14.88483242721929, 142.0),
 (10024.0, 22.281985551153578, 14.945490933733687, 202.0),
 (11232.0, 22.130981150314163, 15.441802123827648, 106.0),
 (11219.0, 22.128552097428958, 14.509424287939495, 105.0),
 (10033.0, 22.113469387755103, 13.983320319116753, 120.0),
 (10468.0, 22.104070305272895, 17.731755801982583, 107.0),
 (11377.0, 22.060877555708707, 14.074470205525184, 214.0),
 (10458.0, 22.013929815162069, 14.734122572271291, 196.0),
 (10009.0, 21.99778891509434, 14.677894625250955, 312.0),
 (11385.0, 21.996373161394317, 15.886890738710418, 252.0),
 (10022.0, 21.987890505749466, 15.428605913316668, 488.0),
 (11358.0, 21.962829303500541, 14.317949247954527, 143.0),
 (11223.0, 21.928736295441432, 16.139980195859227, 185.0),
 (10023.0, 21.917737789203084, 15.013153411096805, 197.0),
 (11201.0, 21.906092871931381, 14.75464007933445, 345.0),
 (10038.0, 21.898205546492658, 14.79903704960558, 168.0),
 (11101.0, 21.856084867894314, 14.195164922245121, 250.0),
 (11238.0, 21.771921531552824, 14.846754452349634, 246.0),
 (11203.0, 21.713423295454547, 14.822454611980737, 141.0),
 (11205.0, 21.702141680395385, 14.233782772666762, 145.0),
 (11105.0, 21.687824351297404, 14.119561870053928, 123.0),
 (10452.0, 21.666361136571954, 14.670738675499456, 101.0),
 (11206.0, 21.617133576938691, 14.753708934007086, 154.0),
 (11435.0, 21.604319478402608, 13.769330254944615, 106.0),
 (11103.0, 21.559838750314942, 15.052239916524449, 209.0),
 (10007.0, 21.559110417479516, 14.486984683944213, 139.0),
 (10014.0, 21.526370455856895, 13.843233349241681, 408.0),
 (10019.0, 21.433634808115375, 14.33100963529945, 660.0),
 (11215.0, 21.415857605177994, 14.22407696761341, 372.0),
 (10011.0, 21.360410525166504, 13.679329739026363, 463.0),
 (11231.0, 21.352941176470587, 14.532861706144104, 159.0),
 (10028.0, 21.348417350527551, 13.733813892609733, 214.0),
 (11237.0, 21.287352758834469, 13.337418799500934, 179.0),
 (10463.0, 21.242828282828281, 14.174341025810273, 128.0),
 (11225.0, 21.174666006927264, 13.712163413634418, 101.0),
 (10012.0, 21.120305306518052, 13.03403466728926, 402.0),
 (10314.0, 21.104534005037785, 13.255806373684043, 185.0),
 (11211.0, 21.099701046337817, 14.070920619686394, 365.0),
 (10461.0, 21.027596223674657, 15.477393530213909, 154.0),
 (10467.0, 21.025978191148173, 14.718819532073192, 169.0),
 (10462.0, 21.021255060728745, 15.371443072220924, 148.0),
 (10001.0, 20.861558050700314, 15.030756843299605, 509.0),
 (11375.0, 20.778710792788342, 12.393559908648955, 196.0),
 (10472.0, 20.658988482724087, 14.052636780301626, 108.0),
 (11209.0, 20.643796802266749, 14.120115899523661, 264.0),
 (11217.0, 20.602597402597404, 13.917399873091394, 254.0),
 (11369.0, 20.591995221027478, 14.218728557003782, 104.0),
 (10301.0, 20.581283743251351, 12.473937702558601, 103.0),
 (11207.0, 20.471054718477397, 12.553618341470401, 136.0),
 (10004.0, 20.437789962041332, 13.814239898174643, 142.0),
 (11249.0, 20.428416877028489, 11.936347601667306, 155.0),
 (10065.0, 20.401324868893184, 12.256622961270615, 173.0),
 (11361.0, 19.9583532790809, 13.299787044931854, 119.0),
 (11430.0, 19.585847504114099, 13.606577635301178, 148.0),
 (10306.0, 19.015512465373963, 12.01401687482922, 111.0),
 (11234.0, 18.945891783567134, 12.78704403474887, 152.0)]