In [102]:
import pandas as pd
import numpy as np

In [451]:
df=pd.read_csv("WebExtract.txt")

In [452]:
df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE
0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03 00:00:00,D,10F,2,A,2014-03-03 00:00:00,2014-09-04 06:01:28.403000000
1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,06A,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10B,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,08C,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
4,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,02G,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
5,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22 00:00:00,D,10F,11,A,2013-07-22 00:00:00,2014-09-04 06:01:28.403000000
6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10 00:00:00,D,10F,5,A,2014-06-10 00:00:00,2014-09-04 06:01:28.403000000
7,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,06D,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000
8,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,04M,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,10F,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000
10,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29 00:00:00,D,10F,10,A,2014-05-29 00:00:00,2014-09-04 06:01:28.403000000
11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06A,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000
12,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14 00:00:00,D,06C,12,A,2014-07-14 00:00:00,2014-09-04 06:01:28.403000000
13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10I,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
14,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,02G,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,10H,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
16,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02 00:00:00,U,04C,19,Z,2014-09-02 00:00:00,2014-09-04 06:01:28.403000000
18,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17 00:00:00,D,02B,13,Z,2013-01-17 00:00:00,2014-09-04 06:01:28.403000000
19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06D,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000
20,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,10E,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07 00:00:00,D,10B,3,A,2014-05-07 00:00:00,2014-09-04 06:01:28.403000000
22,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2013-08-28 00:00:00,D,02B,7,A,2013-08-28 00:00:00,2014-09-04 06:01:28.403000000
23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10 00:00:00,D,04L,13,A,2013-10-10 00:00:00,2014-09-04 06:01:28.403000000
24,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01 00:00:00,F,04J,23,B,2014-07-01 00:00:00,2014-09-04 06:01:28.403000000
25,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02 00:00:00,F,06A,10,A,2014-05-02 00:00:00,2014-09-04 06:01:28.403000000
26,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06D,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
27,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20 00:00:00,D,06E,12,A,2014-05-20 00:00:00,2014-09-04 06:01:28.403000000
28,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18 00:00:00,D,06D,12,A,2014-07-18 00:00:00,2014-09-04 06:01:28.403000000
29,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28 00:00:00,D,06F,11,A,2014-05-28 00:00:00,2014-09-04 06:01:28.403000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531905,50014537,"1734 VICTORY BOULEVARD,INC.",5,1734,VICTORY BOULEVARD,10314,7187204900,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531906,50014563,FACEBOOK INC,1,770,BROADWAY,10003,6503675751,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531907,50014593,shinas pizza and grilling inc,4,88-38,SUTPHIN BOULEVARD ...,11435,3479655770,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531908,50014596,ALNINA CORP.,3,2474,OCEAN AVENUE,11229,9172021300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531909,50014597,Mian Noodle Bar,4,184-02,HORACE HARDING EXPRESSWAY,11365,5169677575,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531910,50014602,"NINETEEN TWENTY FOUR, INC",3,263,MOORE STREET ...,11206,7184171118,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531911,50014697,NEW JADE FOUNTAIN ENTERPRISES CORP,4,185-20,HORACE HARDING EXPRESSWAY,11365,7189399880,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531912,50014704,CREOLE 516 INC.,4,216-19,LINDEN BOULEVARD,11411,5164512071,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531913,50014705,JUICELAND PARK SLOPE INC,3,337,9 STREET,11215,7187881314,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531914,50014712,givers and takers,3,286,3 AVENUE ...,11215,9176271984,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531915,50014732,POPULAR CHICKEN INC,5,229,BROAD STREET,10304,3476068825,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531916,50014737,ZHONG ZHENG 26 RESTAURANT INC,1,26B,E BWAY ...,10002,2122199088,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531917,50014741,Q & Q BAKERY INC.,1,50,EAST BROADWAY,10002,2122262282,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531918,50014840,7 HUA JI PORT CHOP FAST FOOD INC,1,7,ALLEN STREET,10002,9179159663,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531919,50014853,MELT SHOP,1,877,8 AVENUE,10019,2125055861,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531920,50014866,IBM CAFETERIA,1,51,ASTOR PLACE,10003,8452341267,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531921,50014871,CIELO CAFE INC,4,147-36,NORTHERN BOULEVARD ...,11354,7188868871,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531922,50014875,MI RINCONCITO RESTAURANTE,2,131,EAST 169 STREET,10452,7186817474,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531923,50014882,MEANE JOE GREENE LLC,3,524,GRAND STREET ...,11211,9179165602,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531924,50014887,ZMA CORP,1,1159,3 AVENUE ...,10065,9176936031,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531925,50014889,SHARON'S ASIAN RESTAURANT INC,3,1232,AVENUE U,11229,9179578191,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531926,50014901,NUTELLERIA,3,82,5 AVENUE,11217,3473704444,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531927,50014920,FUSHIMI JAPANESE CUISINE,5,2110,RICHMOND ROAD,10306,7189805300,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531928,50014921,Dunkin Donuts,1,542,EAST 14 STREET,10009,2125325003,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531929,50014955,Veinard Cafe Inc.,3,109,ORIENTAL BOULEVARD,11235,3478853050,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531930,50014960,PEPPA POT JAMAICAN CUISINE,4,134-28,GUY R BREWER BOULEVARD,11434,7185288200,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531931,50014972,BELLINI,1,483,COLUMBUS AVENUE,10024,2127244615,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000
531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,2014-09-04 06:01:42.820000000

In [453]:
df['SD'] = df['SE'] = df.SCORE

In [364]:
df.INSPDATE=pd.to_datetime(df.INSPDATE)
df.GRADEDATE=pd.to_datetime(df.GRADEDATE)
df.RECORDDATE=pd.to_datetime(df.RECORDDATE)
c=df.groupby("CAMIS").apply(lambda x: x.sort_values(by='INSPDATE',ascending=False).head(1))
c

,,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,SD,SE
CAMIS,,,,,,,,,,,,,,,,,,
30075445,0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03,D,10F,2,A,2014-03-03,2014-09-04 06:01:28.403,2,2
30112340,1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,06A,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23
30191841,2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10B,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11
40356018,6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10,D,10F,5,A,2014-06-10,2014-09-04 06:01:28.403,5,5
40356068,56265,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2014-01-29,P,08A,12,NaN,NaT,2014-09-04 06:01:28.403,12,12
40356151,19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06D,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10
40356442,15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,10H,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12
40356483,3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,08C,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10
40356649,11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06A,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12
40356731,9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,10F,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12
40357217,13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10I,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11
40357437,30,40357437,C & C CATERING SERVICE,3,7715,18 AVENUE,11214,7182322800,3,2014-04-16,D,06D,5,A,2014-04-16,2014-09-04 06:01:28.403,5,5
40358429,56373,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2014-08-08,F,08A,50,NaN,NaT,2014-09-04 06:01:28.403,50,50
40359480,21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07,D,10B,3,A,2014-05-07,2014-09-04 06:01:28.403,3,3
40359705,468838,40359705,NATHAN'S FAMOUS,3,1310,SURF AVENUE,11224,7183332202,41,2014-02-20,D,15L,NaN,NaN,NaT,2014-09-04 06:01:28.403,NaN,NaN
40360045,23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10,D,04L,13,A,2013-10-10,2014-09-04 06:01:28.403,13,13
40360076,43,40360076,CARVEL ICE CREAM,3,203,CHURCH AVENUE ...,11218,7184389501,43,2014-02-10,D,10F,2,A,2014-02-10,2014-09-04 06:01:28.403,2,2
40361322,33,40361322,CARVEL ICE CREAM,4,265-15,HILLSIDE AVENUE ...,11004,7183430392,43,2013-09-18,D,08A,10,A,2013-09-18,2014-09-04 06:01:28.403,10,10
40361390,36,40361390,NORDIC DELICACIES,3,6909,3 AVENUE,11209,7187481874,27,2014-08-21,D,10B,4,A,2014-08-21,2014-09-04 06:01:28.403,4,4
40361521,17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02,U,04C,19,Z,2014-09-02,2014-09-04 06:01:28.403,19,19
40361606,41,40361606,THE MOVABLE FEAST,3,284,PROSPECT PARK WEST,11215,7189652900,3,2013-11-14,D,10F,2,A,2013-11-14,2014-09-04 06:01:28.403,2,2
40361618,34,40361618,SAL'S DELI,4,129-08,20 AVENUE,11356,7186619498,27,2014-08-16,D,06C,12,A,2014-08-16,2014-09-04 06:01:28.403,12,12
40361708,38,40361708,BULLY'S DELI,1,759,BROADWAY ...,10003,2122549755,27,2014-01-21,D,06D,12,A,2014-01-21,2014-09-04 06:01:28.403,12,12
40361998,48985,40361998,STEVE CHU'S DELI & GROCERY,4,3406,10 STREET ...,11106,7187268888,27,2014-03-19,D,10F,3,A,2014-03-19,2014-09-04 06:01:28.403,3,3
40362098,47,40362098,HARRIET'S KITCHEN,1,502,AMSTERDAM AVENUE ...,10024,2127210045,18,2014-03-04,U,04N,13,A,2014-03-04,2014-09-04 06:01:28.403,13,13
40362264,56701,40362264,P & S DELI GROCERY,1,730,COLUMBUS AVENUE,10025,2129323030,3,2014-08-18,P,04L,24,NaN,NaT,2014-09-04 06:01:28.403,24,24
40362274,68,40362274,ANGELIKA FILM CENTER,1,18,WEST HOUSTON STREET,10012,2129952570,3,2014-04-03,D,06D,9,A,2014-04-03,2014-09-04 06:01:28.403,9,9
40362344,50,40362344,WHITE CASTLE,3,531,MYRTLE AVENUE,11205,7188578132,39,2014-03-18,D,06D,8,A,2014-03-18,2014-09-04 06:01:28.403,8,8
40362432,63,40362432,HO MEI RESTAURANT,4,103-05,37 AVENUE,11368,7187796903,20,2014-04-21,D,06C,10,A,2014-04-21,2014-09-04 06:01:28.403,10,10
40362715,52,40362715,THE COUNTRY CAFE,1,60,WALL STREET,10005,3474279132,83,2013-09-18,D,06B,13,A,2013-09-18,2014-09-04 06:01:28.403,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50014977,531808,50014977,ASMA ASLAM,4,236-03,BRADDOCK AVENUE,11426,3474979749,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014978,531521,50014978,CARAVAN BAZAR INC,5,1101,HYLAN BOULEVARD ...,10305,7187179885,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014979,531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014981,531797,50014981,673 9TH AVENUE,1,673,9 AVENUE ...,10036,2122036161,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014982,531798,50014982,NEW SUN CAFE JAPANESE CUISINE INC,1,67,READE STREET,10007,2126083822,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014986,531773,50014986,LITTLE CAESARS,3,8622,4 AVENUE,11209,8626626222,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014990,531522,50014990,POINT NYC INC,4,41-18,162 STREET,11358,7186613131,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014991,531862,50014991,"SULTAN'S PIZZA, INC.",3,666,FLATBUSH AVENUE ...,11225,3479337523,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014994,531799,50014994,POD 39 F&B LLC,1,145,EAST 39 STREET,10016,2128655700,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014995,531863,50014995,cloud social,1,6,WEST 32 STREET,10001,2129041092,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014997,531809,50014997,Lolo's Seafood Shack,1,303,WEST 116 STREET,10026,6465418940,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50014998,531673,50014998,SNV NY INC,3,222,7 AVENUE,11215,7184994165,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015004,531800,50015004,BAGEL BOB,3,2114,FLATBUSH AVENUE,11234,7186854576,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015008,531774,50015008,LOMAZOYATL DELI GROCERY INC.,4,106-16,CORONA AVENUE,11368,NaN,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015009,531864,50015009,GREEN JUICE CAFE INC,1,4316,BROADWAY,10033,9176574635,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015011,531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015012,531810,50015012,NY FAMILY PIZZA,5,1880,HYLAN BOULEVARD,10305,9877000,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015019,531775,50015019,MBJ DOWNTOWN INC,1,199,CHAMBERS STREET,10013,2125874330,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015023,531836,50015023,URBAN CRAVE,1,42,BROADWAY,10004,7037237264,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015032,531776,50015032,AREPAS & CREPES COLOMBIAN CUISINE INC.,3,241,BAY RIDGE AVENUE ...,11220,6466109918,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015034,531674,50015034,EGGERS ICE CREAM PARLOR,5,6319,AMBOY ROAD,10309,7186059335,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015035,531801,50015035,AUNTIE ANNE'S,4,80-00,COOPER AVENUE ...,11385,5164588020,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015037,531777,50015037,SUBWAY LIBERTY 1148 LLC,3,1148,LIBERTY AVENUE ...,11208,NaN,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015038,531811,50015038,HONG DA RESTAURANT INC,1,42,BROADWAY,10004,9178368798,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015040,531523,50015040,FOREST POINT LLC,3,970,FLUSHING AVENUE,11206,7183662742,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015041,531778,50015041,"WHISPERS BAR, LOUNGE & RESTAURANT, LLC",1,210,WEST 94 STREET ...,10025,8453132814,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015042,531779,50015042,650 FOOD INC,3,650,MANHATTAN AVENUE,11222,7183833334,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015043,531865,50015043,TUMDRI INC,3,595,WASHINGTON AVENUE,11238,3474972856,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015047,531524,50015047,Parkside Pizza Corp,5,1547,ARTHUR KILL ROAD ...,10312,7182271570,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN
50015048,531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN

In [408]:
#Dataframe sorted by 
def SE(x):
    n=np.sqrt(x.count())
    if n==0:
        return None
    ans=np.std(x)
    return(ans)
a=c.groupby('ZIPCODE').agg({"CAMIS":lambda x: x.nunique(),"SCORE":pd.Series.mean,"SD":pd.Series.std,"SE":pd.Series.sem})

a
#b=a.CAMIS.nunique().sort_values(ascending=False).head(100)

             SCORE  CAMIS        SE         SD
ZIPCODE
7005     11.000000      1       NaN        NaN
10000    13.000000      1       NaN        NaN
10001     9.146694    509  0.308902   6.795837
10002    11.868664    474  0.402202   8.378946
10003    11.769108    675  0.328996   8.244617
10004    10.229508    142  0.508269   5.614013
10005     9.455882     69  0.901524   7.434156
10006    12.733333     47  1.240886   8.324116
10007    10.691667    139  0.500251   5.479980
10009    11.805556    312  0.421418   7.151694
10010    11.408696    246  0.525044   7.962681
10011    11.495327    463  0.365145   7.554174
10012    11.425197    402  0.343783   6.710384
10013    12.011364    480  0.343286   7.200820
10014    11.774026    408  0.410951   8.063443
10016    11.728426    414  0.418180   8.300639
10017    11.380282    376  0.423598   7.981204
10018    11.647975    333  0.424420   7.604115
10019    10.677215    660  0.281050   7.065480
10020     8.382979     48  0.789356   5.411554
10021    12.613793    152  0.628901   7.572966
10022    10.942184    488  0.339339   7.333186
10023    10.664835    197  0.558533   7.535021
10024    11.424084    202  0.503738   6.961794
10025    11.780822    237  0.577667   8.548695
10026    13.691176     74  1.131646   9.331790
10027    11.324675    163  0.591216   7.336793
10028    11.787879    214  0.555837   7.821320
10029    12.021505    197  0.706879   9.640543
10030     9.428571     39  1.219096   7.212268
...            ...    ...       ...        ...
11411    12.200000     23  1.236719   5.530775
11412     9.000000     45  1.176697   7.442084
11413    12.256410     41  1.795074  11.210235
11414    13.595745     50  1.237578   8.484409
11415    15.657143     36  2.520485  14.911391
11416    12.642857     44  1.239507   8.032924
11417    11.812500     69  0.956876   7.655012
11418    11.390244     88  0.898786   8.138851
11419    13.162791     91  0.900807   8.353739
11420    11.000000     87  0.816557   7.439184
11421    11.171429     73  0.910480   7.617622
11422    11.820513     41  1.561977   9.754545
11423    11.911765     35  1.084133   6.321525
11426    10.074074     30  0.959175   4.984020
11427    10.333333     19  0.740959   3.143621
11428    13.945946     40  1.360614   8.276291
11429    13.833333     24  1.806456   8.849793
11430     9.689655    148  0.730593   8.797504
11432    11.400000    188  0.616532   8.271645
11433    11.793103     30  1.171689   6.309739
11434    12.411765     90  1.125126  10.373150
11435    10.941176    106  0.668047   6.746944
11436    10.304348     23  0.883388   4.236581
11451     5.000000      1       NaN        NaN
11691    12.930233     45  1.674972  10.983527
11692    10.000000      9  1.589899   4.769696
11693    12.280000     28  1.603662   8.018312
11694    14.333333     38  1.756168  10.537010
11697    15.500000      3  5.500000   7.778175
11753    11.000000      1       NaN        NaN

[208 rows x 4 columns]

In [409]:
topzipcodes=a[a.CAMIS>100].sort_values('SCORE',ascending=False)
topzipcodes["ZIPCODE"]=topzipcodes.index
topzipcodes.shape
topzipcodes.head(5)
#topzipcodes[1]

#a=pd.DataFrame({a:topzipcodes.ZIPCODE,b:topzipcodes.SD})
topzipcodes= topzipcodes[['ZIPCODE', 'SCORE', 'SE', 'CAMIS']]
topzipcodes.ZIPCODE=topzipcodes.ZIPCODE.apply(int)
#topzipcodes.CAMIS.apply(int)
topzipcodes.CAMIS=topzipcodes.CAMIS.apply(int)
topzipcodes.shape
topzipcodes

         ZIPCODE      SCORE        SE  CAMIS
ZIPCODE
11355      11355  14.081081  0.695626    197
11104      11104  13.567308  0.922578    114
11235      11235  13.296296  0.962206    176
11220      11220  13.181507  0.558508    317
10033      10033  13.026786  0.719339    120
11377      11377  13.004975  0.695096    214
11354      11354  12.952096  0.565607    361
10032      10032  12.859649  1.009955    117
11372      11372  12.841751  0.524922    319
10128      10128  12.677632  0.932293    159
10021      10021  12.613793  0.628901    152
11229      11229  12.588235  0.850379    142
10034      10034  12.565217  0.890345    106
11249      11249  12.511111  0.860140    155
11216      11216  12.402597  0.772288    166
11211      11211  12.238095  0.485220    365
11214      11214  12.190476  0.643504    180
10314      10314  12.146199  0.552237    185
11205      11205  12.113475  0.657055    145
11223      11223  12.094675  0.693388    185
11208      11208  12.027027  0.800538    116
11203      11203  12.023077  0.684827    141
10029      10029  12.021505  0.706879    197
10013      10013  12.011364  0.343286    480
11219      11219  11.877551  0.947748    105
10002      10002  11.868664  0.402202    474
11375      11375  11.827957  0.495739    196
11221      11221  11.813725  0.934751    111
10009      10009  11.805556  0.421418    312
10028      10028  11.787879  0.555837    214
...          ...        ...       ...    ...
10022      10022  10.942184  0.339339    488
11435      11435  10.941176  0.668047    106
11218      11218  10.834586  0.696162    147
11207      11207  10.818182  0.636147    136
11225      11225  10.800000  0.600783    101
10065      10065  10.787500  0.429402    173
10301      10301  10.774194  0.630221    103
11105      11105  10.747826  0.676267    123
10007      10007  10.691667  0.500251    139
11232      11232  10.683168  0.623299    106
10461      10461  10.680556  0.602914    154
10019      10019  10.677215  0.281050    660
11209      11209  10.669456  0.543344    264
10023      10023  10.664835  0.558533    197
11237      11237  10.584795  0.536187    179
11201      11201  10.551402  0.394217    345
10462      10462  10.537931  0.499331    148
11369      11369  10.536082  0.704834    104
11368      11368  10.516245  0.456660    290
11231      11231  10.513889  0.524921    159
10306      10306  10.403846  0.463475    111
11217      11217  10.297071  0.433956    254
10004      10004  10.229508  0.508269    142
11234      11234  10.127660  0.515303    152
10472      10472  10.115385  0.639634    108
10452      10452   9.922222  0.594445    101
11236      11236   9.865385  0.739131    111
11430      11430   9.689655  0.730593    148
10001      10001   9.146694  0.308902    509
10451      10451   9.072368  0.543274    157

[92 rows x 4 columns]

In [411]:

a=[(str(int(row[1].ZIPCODE)),row[1].SCORE,row[1].SE,int(row[1].CAMIS)) for row in topzipcodes.iterrows()]
    #print (row[1].ZIPCODE,row[1].SCORE,row[1].SE,row[1].CAMIS)
a

[('11355', 14.081081081081081, 0.69562557512587653, 197),
 ('11104', 13.567307692307692, 0.92257841826107001, 114),
 ('11235', 13.296296296296296, 0.96220617569857636, 176),
 ('11220', 13.181506849315069, 0.5585076143367822, 317),
 ('10033', 13.026785714285714, 0.71933892652963838, 120),
 ('11377', 13.00497512437811, 0.69509645389743335, 214),
 ('11354', 12.952095808383234, 0.5656074873888044, 361),
 ('10032', 12.859649122807017, 1.0099548898436455, 117),
 ('11372', 12.841750841750843, 0.52492218145842107, 319),
 ('10128', 12.677631578947368, 0.93229320208107536, 159),
 ('10021', 12.613793103448275, 0.62890056463706467, 152),
 ('11229', 12.588235294117647, 0.85037929434588821, 142),
 ('10034', 12.565217391304348, 0.89034535242796831, 106),
 ('11249', 12.511111111111111, 0.86014041474364156, 155),
 ('11216', 12.402597402597403, 0.77228757786307123, 166),
 ('11211', 12.238095238095237, 0.48522000575879043, 365),
 ('11214', 12.19047619047619, 0.64350367218516746, 180),
 ('10314', 12.146198830409357, 0.55223675111532911, 185),
 ('11205', 12.113475177304965, 0.65705524932597947, 145),
 ('11223', 12.094674556213018, 0.69338756863694739, 185),
 ('11208', 12.027027027027026, 0.80053825662547773, 116),
 ('11203', 12.023076923076923, 0.68482707292499612, 141),
 ('10029', 12.021505376344086, 0.7068789327659547, 197),
 ('10013', 12.011363636363637, 0.34328561787094641, 480),
 ('11219', 11.877551020408163, 0.94774753799512201, 105),
 ('10002', 11.868663594470046, 0.40220225953542649, 474),
 ('11375', 11.827956989247312, 0.49573873272753038, 196),
 ('11221', 11.813725490196079, 0.93475053871532454, 111),
 ('10009', 11.805555555555555, 0.42141761671067868, 312),
 ('10028', 11.787878787878787, 0.55583702601996265, 214),
 ('11206', 11.785185185185185, 0.78743484889781645, 154),
 ('10025', 11.780821917808218, 0.57766725413206221, 237),
 ('10014', 11.774025974025975, 0.41095111492301389, 408),
 ('10003', 11.769108280254777, 0.32899605351120786, 675),
 ('11230', 11.767676767676768, 0.68403900134074436, 102),
 ('10016', 11.728426395939087, 0.41818017277751773, 414),
 ('11358', 11.707692307692307, 0.66584142308601968, 143),
 ('10038', 11.662337662337663, 0.76214779557870072, 168),
 ('10018', 11.64797507788162, 0.42442031641108119, 333),
 ('11226', 11.62051282051282, 0.66861830277534628, 201),
 ('10011', 11.495327102803738, 0.36514480511092939, 463),
 ('11373', 11.483720930232558, 0.46165020199671086, 225),
 ('10012', 11.4251968503937, 0.34378340471365798, 402),
 ('10024', 11.424083769633508, 0.50373772997151023, 202),
 ('10010', 11.408695652173913, 0.52504364567092909, 246),
 ('11103', 11.4, 0.50510068862853608, 209),
 ('11432', 11.4, 0.61653202012837505, 188),
 ('10017', 11.380281690140846, 0.42359830190883763, 376),
 ('10467', 11.361290322580645, 0.59306732659324135, 169),
 ('10027', 11.324675324675324, 0.59121566084952637, 163),
 ('11106', 11.287671232876713, 0.65893509257131977, 156),
 ('11385', 11.283898305084746, 0.43470063011355292, 252),
 ('11215', 11.265129682997118, 0.37857982494630688, 372),
 ('11361', 11.229357798165138, 0.69762874757269444, 119),
 ('11204', 11.196581196581196, 0.63429812923115392, 123),
 ('11101', 11.18348623853211, 0.44125259738661465, 250),
 ('10463', 11.139344262295081, 0.69383992592573462, 128),
 ('10036', 11.094642857142857, 0.33460436570748608, 593),
 ('10468', 10.989690721649485, 0.7779023424672179, 107),
 ('11238', 10.985781990521327, 0.59409106749614427, 246),
 ('11222', 10.960227272727273, 0.53660554059602028, 193),
 ('10458', 10.945054945054945, 0.55128163106616634, 196),
 ('10022', 10.942184154175589, 0.33933938880778236, 488),
 ('11435', 10.941176470588236, 0.66804703668019805, 106),
 ('11218', 10.834586466165414, 0.69616176260863827, 147),
 ('11207', 10.818181818181818, 0.63614714932339878, 136),
 ('11225', 10.800000000000001, 0.60078336319848336, 101),
 ('10065', 10.7875, 0.42940168810616913, 173),
 ('10301', 10.774193548387096, 0.63022088343029081, 103),
 ('11105', 10.747826086956522, 0.67626689632606918, 123),
 ('10007', 10.691666666666666, 0.50025145404443971, 139),
 ('11232', 10.683168316831683, 0.62329858602475319, 106),
 ('10461', 10.680555555555555, 0.60291418506051198, 154),
 ('10019', 10.677215189873417, 0.28104968654007495, 660),
 ('11209', 10.669456066945607, 0.54334447360597027, 264),
 ('10023', 10.664835164835164, 0.55853294224255179, 197),
 ('11237', 10.584795321637428, 0.53618691155448217, 179),
 ('11201', 10.551401869158878, 0.39421688150155948, 345),
 ('10462', 10.537931034482758, 0.49933103617084085, 148),
 ('11369', 10.536082474226804, 0.70483447394971943, 104),
 ('11368', 10.516245487364621, 0.45666003627598223, 290),
 ('11231', 10.513888888888889, 0.52492147182623261, 159),
 ('10306', 10.403846153846153, 0.46347536693149466, 111),
 ('11217', 10.297071129707113, 0.43395628935426672, 254),
 ('10004', 10.229508196721312, 0.50826882811364194, 142),
 ('11234', 10.127659574468085, 0.51530290949491042, 152),
 ('10472', 10.115384615384615, 0.63963378891832079, 108),
 ('10452', 9.9222222222222225, 0.59444531951818147, 101),
 ('11236', 9.865384615384615, 0.7391305587515985, 111),
 ('11430', 9.6896551724137936, 0.73059292310369783, 148),
 ('10001', 9.1466942148760335, 0.30890169742820034, 509),
 ('10451', 9.0723684210526319, 0.54327393132275448, 157)]

In [401]:
#topzipcodes.to_csv('a.csv',index=False)

In [458]:
#BY borough
b=c.groupby('BORO').agg({"CAMIS":lambda x: x.nunique(),"SCORE":pd.Series.mean,"SE":pd.Series.sem})

In [459]:
b=b.reset_index()

In [460]:

btuple=[(row[1].BORO,row[1].SCORE,row[1].SE,int(row[1].CAMIS)) for row in b.iterrows()]
btuple

[(0.0, 10.545454545454545, 1.6424130604561769, 12),
 (1.0, 11.358427436219156, 0.079815274485948259, 10201),
 (2.0, 10.72821670428894, 0.15200948403159781, 2365),
 (3.0, 11.472944108223567, 0.11071459149883139, 6072),
 (4.0, 11.755732423725602, 0.11121071258632133, 5625),
 (5.0, 11.712643678160919, 0.24903066158997716, 957)]

In [461]:
b

   BORO      SCORE  CAMIS        SE
0     0  10.545455     12  1.642413
1     1  11.358427  10201  0.079815
2     2  10.728217   2365  0.152009
3     3  11.472944   6072  0.110715
4     4  11.755732   5625  0.111211
5     5  11.712644    957  0.249031

In [425]:
df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINECODE,INSPDATE,ACTION,VIOLCODE,SCORE,CURRENTGRADE,GRADEDATE,RECORDDATE,SD,SE,means
0,30075445,MORRIS PARK BAKE SHOP,2,1007,MORRIS PARK AVE ...,10462,7188924968,8,2014-03-03,D,10F,2,A,2014-03-03,2014-09-04 06:01:28.403,2,2,2
1,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,06A,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23,23
2,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10B,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11,11
3,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,08C,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10,10
4,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,02G,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11,11
5,30191841,DJ REYNOLDS PUB AND RESTAURANT,1,351,WEST 57 STREET,10019,2122452912,3,2013-07-22,D,10F,11,A,2013-07-22,2014-09-04 06:01:28.403,11,11,11
6,40356018,RIVIERA CATERER,3,2780,STILLWELL AVENUE,11224,7183723031,3,2014-06-10,D,10F,5,A,2014-06-10,2014-09-04 06:01:28.403,5,5,5
7,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17,D,06D,13,Z,2013-01-17,2014-09-04 06:01:28.403,13,13,13
8,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,04M,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10,10
9,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,10F,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12,12
10,40356483,WILKEN'S FINE FOOD,3,7114,AVENUE U,11234,7184443838,27,2014-05-29,D,10F,10,A,2014-05-29,2014-09-04 06:01:28.403,10,10,10
11,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06A,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12,12
12,40356731,TASTE THE TROPICS ICE CREAM,3,1839,NOSTRAND AVENUE ...,11226,7188560821,43,2014-07-14,D,06C,12,A,2014-07-14,2014-09-04 06:01:28.403,12,12,12
13,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10I,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11,11
14,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,02G,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23,23
15,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,10H,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12,12
16,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10F,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11,11
17,40361521,GLORIOUS FOOD,1,522,EAST 74 STREET,10021,2127372140,3,2014-09-02,U,04C,19,Z,2014-09-02,2014-09-04 06:01:28.403,19,19,19
18,40356068,TOV KOSHER KITCHEN,4,97-22,63 ROAD,11374,7188967788,50,2013-01-17,D,02B,13,Z,2013-01-17,2014-09-04 06:01:28.403,13,13,13
19,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06D,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10,10
20,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,10E,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11,11
21,40359480,1 EAST 66TH STREET KITCHEN,1,1,EAST 66 STREET ...,10065,2128793900,3,2014-05-07,D,10B,3,A,2014-05-07,2014-09-04 06:01:28.403,3,3,3
22,40358429,MAY MAY KITCHEN,3,1269,SUTTER AVENUE,11208,7182354485,20,2013-08-28,D,02B,7,A,2013-08-28,2014-09-04 06:01:28.403,7,7,7
23,40360045,SEUDA FOODS,3,705,KINGS HIGHWAY ...,11223,7183751500,50,2013-10-10,D,04L,13,A,2013-10-10,2014-09-04 06:01:28.403,13,13,13
24,30112340,WENDY'S,3,469,FLATBUSH AVENUE,11225,7182875005,39,2014-07-01,F,04J,23,B,2014-07-01,2014-09-04 06:01:28.403,23,23,23
25,40356151,BRUNOS ON THE BOULEVARD,4,88-25,ASTORIA BOULEVARD,11369,7183350505,3,2014-05-02,F,06A,10,A,2014-05-02,2014-09-04 06:01:28.403,10,10,10
26,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,06D,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12,12
27,40356442,KOSHER ISLAND,5,2206,VICTORY BOULEVARD,10314,7186985800,50,2014-05-20,D,06E,12,A,2014-05-20,2014-09-04 06:01:28.403,12,12,12
28,40356649,REGINA CATERERS,3,6409,11 AVENUE,11219,7182560829,3,2014-07-18,D,06D,12,A,2014-07-18,2014-09-04 06:01:28.403,12,12,12
29,40357217,WILD ASIA,2,2300,SOUTHERN BOULEVARD,10460,7182207846,3,2014-05-28,D,06F,11,A,2014-05-28,2014-09-04 06:01:28.403,11,11,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531905,50014537,"1734 VICTORY BOULEVARD,INC.",5,1734,VICTORY BOULEVARD,10314,7187204900,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531906,50014563,FACEBOOK INC,1,770,BROADWAY,10003,6503675751,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531907,50014593,shinas pizza and grilling inc,4,88-38,SUTPHIN BOULEVARD ...,11435,3479655770,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531908,50014596,ALNINA CORP.,3,2474,OCEAN AVENUE,11229,9172021300,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531909,50014597,Mian Noodle Bar,4,184-02,HORACE HARDING EXPRESSWAY,11365,5169677575,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531910,50014602,"NINETEEN TWENTY FOUR, INC",3,263,MOORE STREET ...,11206,7184171118,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531911,50014697,NEW JADE FOUNTAIN ENTERPRISES CORP,4,185-20,HORACE HARDING EXPRESSWAY,11365,7189399880,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531912,50014704,CREOLE 516 INC.,4,216-19,LINDEN BOULEVARD,11411,5164512071,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531913,50014705,JUICELAND PARK SLOPE INC,3,337,9 STREET,11215,7187881314,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531914,50014712,givers and takers,3,286,3 AVENUE ...,11215,9176271984,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531915,50014732,POPULAR CHICKEN INC,5,229,BROAD STREET,10304,3476068825,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531916,50014737,ZHONG ZHENG 26 RESTAURANT INC,1,26B,E BWAY ...,10002,2122199088,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531917,50014741,Q & Q BAKERY INC.,1,50,EAST BROADWAY,10002,2122262282,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531918,50014840,7 HUA JI PORT CHOP FAST FOOD INC,1,7,ALLEN STREET,10002,9179159663,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531919,50014853,MELT SHOP,1,877,8 AVENUE,10019,2125055861,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531920,50014866,IBM CAFETERIA,1,51,ASTOR PLACE,10003,8452341267,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531921,50014871,CIELO CAFE INC,4,147-36,NORTHERN BOULEVARD ...,11354,7188868871,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531922,50014875,MI RINCONCITO RESTAURANTE,2,131,EAST 169 STREET,10452,7186817474,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531923,50014882,MEANE JOE GREENE LLC,3,524,GRAND STREET ...,11211,9179165602,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531924,50014887,ZMA CORP,1,1159,3 AVENUE ...,10065,9176936031,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531925,50014889,SHARON'S ASIAN RESTAURANT INC,3,1232,AVENUE U,11229,9179578191,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531926,50014901,NUTELLERIA,3,82,5 AVENUE,11217,3473704444,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531927,50014920,FUSHIMI JAPANESE CUISINE,5,2110,RICHMOND ROAD,10306,7189805300,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531928,50014921,Dunkin Donuts,1,542,EAST 14 STREET,10009,2125325003,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531929,50014955,Veinard Cafe Inc.,3,109,ORIENTAL BOULEVARD,11235,3478853050,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531930,50014960,PEPPA POT JAMAICAN CUISINE,4,134-28,GUY R BREWER BOULEVARD,11434,7185288200,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531931,50014972,BELLINI,1,483,COLUMBUS AVENUE,10024,2127244615,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531932,50014979,The Finch,3,212,GREENE AVENUE ...,11238,9176267596,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531933,50015011,ROAST KITCHEN,1,27,EAST 13 STREET ...,10003,2127764053,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN
531934,50015048,Vivire LLC,4,41-21,GREENPOINT AVENUE ...,11104,9176580796,99,1900-01-01,NaN,NaN,NaN,NaN,NaT,2014-09-04 06:01:42.820,NaN,NaN,NaN